<?php
/**
 * WhiteLabelApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * WhiteLabelApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhiteLabelApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'whiteLabelGet' => [
            'application/json',
        ],
        'whiteLabelGetWhiteLabelCustomizationByUrl' => [
            'application/json',
        ],
        'whiteLabelGetWhitelabelPlaceholders' => [
            'application/json',
        ],
        'whiteLabelUpdate' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
        'whiteLabelUpdateDcaLicenses' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
        'whiteLabelUpdateTemplates' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation whiteLabelGet
     *
     * Get the white label.
     *
     * @param  string $code Gets or sets the code. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto
     */
    public function whiteLabelGet($code, string $contentType = self::contentTypes['whiteLabelGet'][0])
    {
        list($response) = $this->whiteLabelGetWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation whiteLabelGetWithHttpInfo
     *
     * Get the white label.
     *
     * @param  string $code Gets or sets the code. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelGetWithHttpInfo($code, string $contentType = self::contentTypes['whiteLabelGet'][0])
    {
        $request = $this->whiteLabelGetRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelGetAsync
     *
     * Get the white label.
     *
     * @param  string $code Gets or sets the code. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetAsync($code, string $contentType = self::contentTypes['whiteLabelGet'][0])
    {
        return $this->whiteLabelGetAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelGetAsyncWithHttpInfo
     *
     * Get the white label.
     *
     * @param  string $code Gets or sets the code. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetAsyncWithHttpInfo($code, string $contentType = self::contentTypes['whiteLabelGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto';
        $request = $this->whiteLabelGetRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelGet'
     *
     * @param  string $code Gets or sets the code. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelGetRequest($code, string $contentType = self::contentTypes['whiteLabelGet'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling whiteLabelGet'
            );
        }


        $resourcePath = '/WhiteLabel/Get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelGetWhiteLabelCustomizationByUrl
     *
     * Get the whitelabel customizations by the caller URL
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto
     */
    public function whiteLabelGetWhiteLabelCustomizationByUrl(string $contentType = self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'][0])
    {
        list($response) = $this->whiteLabelGetWhiteLabelCustomizationByUrlWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation whiteLabelGetWhiteLabelCustomizationByUrlWithHttpInfo
     *
     * Get the whitelabel customizations by the caller URL
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelGetWhiteLabelCustomizationByUrlWithHttpInfo(string $contentType = self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'][0])
    {
        $request = $this->whiteLabelGetWhiteLabelCustomizationByUrlRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelGetWhiteLabelCustomizationByUrlAsync
     *
     * Get the whitelabel customizations by the caller URL
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhiteLabelCustomizationByUrlAsync(string $contentType = self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'][0])
    {
        return $this->whiteLabelGetWhiteLabelCustomizationByUrlAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelGetWhiteLabelCustomizationByUrlAsyncWithHttpInfo
     *
     * Get the whitelabel customizations by the caller URL
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhiteLabelCustomizationByUrlAsyncWithHttpInfo(string $contentType = self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelCustomizationDto';
        $request = $this->whiteLabelGetWhiteLabelCustomizationByUrlRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelGetWhiteLabelCustomizationByUrl'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelGetWhiteLabelCustomizationByUrlRequest(string $contentType = self::contentTypes['whiteLabelGetWhiteLabelCustomizationByUrl'][0])
    {


        $resourcePath = '/WhiteLabel/GetWhiteLabelCustomizationByUrl';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelGetWhitelabelPlaceholders
     *
     * Get whitelabel placeholders
     *
     * @param  string|null $portal_email_template_type portal_email_template_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhitelabelPlaceholders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto
     */
    public function whiteLabelGetWhitelabelPlaceholders($portal_email_template_type = null, string $contentType = self::contentTypes['whiteLabelGetWhitelabelPlaceholders'][0])
    {
        list($response) = $this->whiteLabelGetWhitelabelPlaceholdersWithHttpInfo($portal_email_template_type, $contentType);
        return $response;
    }

    /**
     * Operation whiteLabelGetWhitelabelPlaceholdersWithHttpInfo
     *
     * Get whitelabel placeholders
     *
     * @param  string|null $portal_email_template_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhitelabelPlaceholders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelGetWhitelabelPlaceholdersWithHttpInfo($portal_email_template_type = null, string $contentType = self::contentTypes['whiteLabelGetWhitelabelPlaceholders'][0])
    {
        $request = $this->whiteLabelGetWhitelabelPlaceholdersRequest($portal_email_template_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelGetWhitelabelPlaceholdersAsync
     *
     * Get whitelabel placeholders
     *
     * @param  string|null $portal_email_template_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhitelabelPlaceholders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhitelabelPlaceholdersAsync($portal_email_template_type = null, string $contentType = self::contentTypes['whiteLabelGetWhitelabelPlaceholders'][0])
    {
        return $this->whiteLabelGetWhitelabelPlaceholdersAsyncWithHttpInfo($portal_email_template_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelGetWhitelabelPlaceholdersAsyncWithHttpInfo
     *
     * Get whitelabel placeholders
     *
     * @param  string|null $portal_email_template_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhitelabelPlaceholders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhitelabelPlaceholdersAsyncWithHttpInfo($portal_email_template_type = null, string $contentType = self::contentTypes['whiteLabelGetWhitelabelPlaceholders'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ListResultResponseWhiteLabelPlaceholderDto';
        $request = $this->whiteLabelGetWhitelabelPlaceholdersRequest($portal_email_template_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelGetWhitelabelPlaceholders'
     *
     * @param  string|null $portal_email_template_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelGetWhitelabelPlaceholders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelGetWhitelabelPlaceholdersRequest($portal_email_template_type = null, string $contentType = self::contentTypes['whiteLabelGetWhitelabelPlaceholders'][0])
    {



        $resourcePath = '/WhiteLabel/GetWhitelabelPlaceholders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $portal_email_template_type,
            'portalEmailTemplateType', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelUpdate
     *
     * TResponse              Update the white label
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto
     */
    public function whiteLabelUpdate($request, string $contentType = self::contentTypes['whiteLabelUpdate'][0])
    {
        list($response) = $this->whiteLabelUpdateWithHttpInfo($request, $contentType);
        return $response;
    }

    /**
     * Operation whiteLabelUpdateWithHttpInfo
     *
     * TResponse              Update the white label
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelUpdateWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdate'][0])
    {
        $request = $this->whiteLabelUpdateRequest($request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelUpdateAsync
     *
     * TResponse              Update the white label
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateAsync($request, string $contentType = self::contentTypes['whiteLabelUpdate'][0])
    {
        return $this->whiteLabelUpdateAsyncWithHttpInfo($request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelUpdateAsyncWithHttpInfo
     *
     * TResponse              Update the white label
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateAsyncWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto';
        $request = $this->whiteLabelUpdateRequest($request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelUpdate'
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelUpdateRequest($request, string $contentType = self::contentTypes['whiteLabelUpdate'][0])
    {

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling whiteLabelUpdate'
            );
        }


        $resourcePath = '/WhiteLabel/Update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelUpdateDcaLicenses
     *
     * Update a DCA licence text
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateDcaLicenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto
     */
    public function whiteLabelUpdateDcaLicenses($request, string $contentType = self::contentTypes['whiteLabelUpdateDcaLicenses'][0])
    {
        list($response) = $this->whiteLabelUpdateDcaLicensesWithHttpInfo($request, $contentType);
        return $response;
    }

    /**
     * Operation whiteLabelUpdateDcaLicensesWithHttpInfo
     *
     * Update a DCA licence text
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateDcaLicenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelUpdateDcaLicensesWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdateDcaLicenses'][0])
    {
        $request = $this->whiteLabelUpdateDcaLicensesRequest($request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelUpdateDcaLicensesAsync
     *
     * Update a DCA licence text
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateDcaLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateDcaLicensesAsync($request, string $contentType = self::contentTypes['whiteLabelUpdateDcaLicenses'][0])
    {
        return $this->whiteLabelUpdateDcaLicensesAsyncWithHttpInfo($request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelUpdateDcaLicensesAsyncWithHttpInfo
     *
     * Update a DCA licence text
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateDcaLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateDcaLicensesAsyncWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdateDcaLicenses'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto';
        $request = $this->whiteLabelUpdateDcaLicensesRequest($request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelUpdateDcaLicenses'
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateDcaLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelUpdateDcaLicensesRequest($request, string $contentType = self::contentTypes['whiteLabelUpdateDcaLicenses'][0])
    {

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling whiteLabelUpdateDcaLicenses'
            );
        }


        $resourcePath = '/WhiteLabel/UpdateDcaLicenses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelUpdateTemplates
     *
     * Updates and email template
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateTemplates'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto
     */
    public function whiteLabelUpdateTemplates($request, string $contentType = self::contentTypes['whiteLabelUpdateTemplates'][0])
    {
        list($response) = $this->whiteLabelUpdateTemplatesWithHttpInfo($request, $contentType);
        return $response;
    }

    /**
     * Operation whiteLabelUpdateTemplatesWithHttpInfo
     *
     * Updates and email template
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateTemplates'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelUpdateTemplatesWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdateTemplates'][0])
    {
        $request = $this->whiteLabelUpdateTemplatesRequest($request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation whiteLabelUpdateTemplatesAsync
     *
     * Updates and email template
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateTemplatesAsync($request, string $contentType = self::contentTypes['whiteLabelUpdateTemplates'][0])
    {
        return $this->whiteLabelUpdateTemplatesAsyncWithHttpInfo($request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelUpdateTemplatesAsyncWithHttpInfo
     *
     * Updates and email template
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelUpdateTemplatesAsyncWithHttpInfo($request, string $contentType = self::contentTypes['whiteLabelUpdateTemplates'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SingleResultResponseWhiteLabelDto';
        $request = $this->whiteLabelUpdateTemplatesRequest($request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelUpdateTemplates'
     *
     * @param  \OpenAPI\Client\Model\UpdateRequestWhiteLabelDto $request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['whiteLabelUpdateTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function whiteLabelUpdateTemplatesRequest($request, string $contentType = self::contentTypes['whiteLabelUpdateTemplates'][0])
    {

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling whiteLabelUpdateTemplates'
            );
        }


        $resourcePath = '/WhiteLabel/UpdateTemplates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
