<?php
/**
 * BillingDriverDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BillingDriverDto Class Doc Comment
 *
 * @category Class
 * @description Billing Driver
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BillingDriverDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BillingDriverDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'is_billing' => 'bool',
        'has_proforma' => 'bool',
        'is_active' => 'bool',
        'issuer' => '\OpenAPI\Client\Model\DealerDto',
        'recipient' => '\OpenAPI\Client\Model\DealerDto',
        'recipient_customer' => '\OpenAPI\Client\Model\CustomerDto',
        'bill_to' => '\OpenAPI\Client\Model\CompanyDto',
        'invoice_template' => 'string',
        'invoice_media_types' => 'string',
        'day_of_month' => 'int',
        'months' => 'string',
        'hour' => 'int',
        'email' => 'string',
        'email_proforma' => 'string',
        'is_mail_to_send' => 'bool',
        'subject' => 'string',
        'subject_proforma' => 'string',
        'invoice_heading' => 'string',
        'body' => 'string',
        'body_proforma' => 'string',
        'payment_type' => 'string',
        'payment_term' => 'string',
        'financial_discount_rate' => 'float',
        'tax_rate_code' => 'string',
        'is_dealer_tax_rate' => 'bool',
        'tax_rate_reason' => 'string',
        'tax_rate_reason_type' => 'string',
        'tax_rate_reason_text_reference' => 'string',
        'tax_rate_reason_date_reference' => '\DateTime',
        'language' => 'string',
        'currency' => '\OpenAPI\Client\Model\CurrencyDto',
        'sales_agent' => '\OpenAPI\Client\Model\AccountDto',
        'issuer_bank' => '\OpenAPI\Client\Model\DealerBankAccountDto',
        'contract_billable_services' => '\OpenAPI\Client\Model\ContractBillableServiceDto[]',
        'custom_field_values' => '\OpenAPI\Client\Model\CustomFieldValueDto[]',
        'number_of_devices' => 'int',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'is_billing' => null,
        'has_proforma' => null,
        'is_active' => null,
        'issuer' => null,
        'recipient' => null,
        'recipient_customer' => null,
        'bill_to' => null,
        'invoice_template' => null,
        'invoice_media_types' => null,
        'day_of_month' => 'int32',
        'months' => null,
        'hour' => 'int32',
        'email' => null,
        'email_proforma' => null,
        'is_mail_to_send' => null,
        'subject' => null,
        'subject_proforma' => null,
        'invoice_heading' => null,
        'body' => null,
        'body_proforma' => null,
        'payment_type' => null,
        'payment_term' => null,
        'financial_discount_rate' => 'double',
        'tax_rate_code' => null,
        'is_dealer_tax_rate' => null,
        'tax_rate_reason' => null,
        'tax_rate_reason_type' => null,
        'tax_rate_reason_text_reference' => null,
        'tax_rate_reason_date_reference' => 'date-time',
        'language' => null,
        'currency' => null,
        'sales_agent' => null,
        'issuer_bank' => null,
        'contract_billable_services' => null,
        'custom_field_values' => null,
        'number_of_devices' => 'int32',
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'is_billing' => false,
        'has_proforma' => false,
        'is_active' => false,
        'issuer' => false,
        'recipient' => false,
        'recipient_customer' => false,
        'bill_to' => false,
        'invoice_template' => false,
        'invoice_media_types' => false,
        'day_of_month' => false,
        'months' => false,
        'hour' => false,
        'email' => false,
        'email_proforma' => false,
        'is_mail_to_send' => false,
        'subject' => false,
        'subject_proforma' => false,
        'invoice_heading' => false,
        'body' => false,
        'body_proforma' => false,
        'payment_type' => false,
        'payment_term' => false,
        'financial_discount_rate' => false,
        'tax_rate_code' => false,
        'is_dealer_tax_rate' => false,
        'tax_rate_reason' => false,
        'tax_rate_reason_type' => false,
        'tax_rate_reason_text_reference' => false,
        'tax_rate_reason_date_reference' => false,
        'language' => false,
        'currency' => false,
        'sales_agent' => false,
        'issuer_bank' => false,
        'contract_billable_services' => false,
        'custom_field_values' => false,
        'number_of_devices' => false,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_billing' => 'IsBilling',
        'has_proforma' => 'HasProforma',
        'is_active' => 'IsActive',
        'issuer' => 'Issuer',
        'recipient' => 'Recipient',
        'recipient_customer' => 'RecipientCustomer',
        'bill_to' => 'BillTo',
        'invoice_template' => 'InvoiceTemplate',
        'invoice_media_types' => 'InvoiceMediaTypes',
        'day_of_month' => 'DayOfMonth',
        'months' => 'Months',
        'hour' => 'Hour',
        'email' => 'Email',
        'email_proforma' => 'EmailProforma',
        'is_mail_to_send' => 'IsMailToSend',
        'subject' => 'Subject',
        'subject_proforma' => 'SubjectProforma',
        'invoice_heading' => 'InvoiceHeading',
        'body' => 'Body',
        'body_proforma' => 'BodyProforma',
        'payment_type' => 'PaymentType',
        'payment_term' => 'PaymentTerm',
        'financial_discount_rate' => 'FinancialDiscountRate',
        'tax_rate_code' => 'TaxRateCode',
        'is_dealer_tax_rate' => 'IsDealerTaxRate',
        'tax_rate_reason' => 'TaxRateReason',
        'tax_rate_reason_type' => 'TaxRateReasonType',
        'tax_rate_reason_text_reference' => 'TaxRateReasonTextReference',
        'tax_rate_reason_date_reference' => 'TaxRateReasonDateReference',
        'language' => 'Language',
        'currency' => 'Currency',
        'sales_agent' => 'SalesAgent',
        'issuer_bank' => 'IssuerBank',
        'contract_billable_services' => 'ContractBillableServices',
        'custom_field_values' => 'CustomFieldValues',
        'number_of_devices' => 'NumberOfDevices',
        'id' => 'Id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_billing' => 'setIsBilling',
        'has_proforma' => 'setHasProforma',
        'is_active' => 'setIsActive',
        'issuer' => 'setIssuer',
        'recipient' => 'setRecipient',
        'recipient_customer' => 'setRecipientCustomer',
        'bill_to' => 'setBillTo',
        'invoice_template' => 'setInvoiceTemplate',
        'invoice_media_types' => 'setInvoiceMediaTypes',
        'day_of_month' => 'setDayOfMonth',
        'months' => 'setMonths',
        'hour' => 'setHour',
        'email' => 'setEmail',
        'email_proforma' => 'setEmailProforma',
        'is_mail_to_send' => 'setIsMailToSend',
        'subject' => 'setSubject',
        'subject_proforma' => 'setSubjectProforma',
        'invoice_heading' => 'setInvoiceHeading',
        'body' => 'setBody',
        'body_proforma' => 'setBodyProforma',
        'payment_type' => 'setPaymentType',
        'payment_term' => 'setPaymentTerm',
        'financial_discount_rate' => 'setFinancialDiscountRate',
        'tax_rate_code' => 'setTaxRateCode',
        'is_dealer_tax_rate' => 'setIsDealerTaxRate',
        'tax_rate_reason' => 'setTaxRateReason',
        'tax_rate_reason_type' => 'setTaxRateReasonType',
        'tax_rate_reason_text_reference' => 'setTaxRateReasonTextReference',
        'tax_rate_reason_date_reference' => 'setTaxRateReasonDateReference',
        'language' => 'setLanguage',
        'currency' => 'setCurrency',
        'sales_agent' => 'setSalesAgent',
        'issuer_bank' => 'setIssuerBank',
        'contract_billable_services' => 'setContractBillableServices',
        'custom_field_values' => 'setCustomFieldValues',
        'number_of_devices' => 'setNumberOfDevices',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_billing' => 'getIsBilling',
        'has_proforma' => 'getHasProforma',
        'is_active' => 'getIsActive',
        'issuer' => 'getIssuer',
        'recipient' => 'getRecipient',
        'recipient_customer' => 'getRecipientCustomer',
        'bill_to' => 'getBillTo',
        'invoice_template' => 'getInvoiceTemplate',
        'invoice_media_types' => 'getInvoiceMediaTypes',
        'day_of_month' => 'getDayOfMonth',
        'months' => 'getMonths',
        'hour' => 'getHour',
        'email' => 'getEmail',
        'email_proforma' => 'getEmailProforma',
        'is_mail_to_send' => 'getIsMailToSend',
        'subject' => 'getSubject',
        'subject_proforma' => 'getSubjectProforma',
        'invoice_heading' => 'getInvoiceHeading',
        'body' => 'getBody',
        'body_proforma' => 'getBodyProforma',
        'payment_type' => 'getPaymentType',
        'payment_term' => 'getPaymentTerm',
        'financial_discount_rate' => 'getFinancialDiscountRate',
        'tax_rate_code' => 'getTaxRateCode',
        'is_dealer_tax_rate' => 'getIsDealerTaxRate',
        'tax_rate_reason' => 'getTaxRateReason',
        'tax_rate_reason_type' => 'getTaxRateReasonType',
        'tax_rate_reason_text_reference' => 'getTaxRateReasonTextReference',
        'tax_rate_reason_date_reference' => 'getTaxRateReasonDateReference',
        'language' => 'getLanguage',
        'currency' => 'getCurrency',
        'sales_agent' => 'getSalesAgent',
        'issuer_bank' => 'getIssuerBank',
        'contract_billable_services' => 'getContractBillableServices',
        'custom_field_values' => 'getCustomFieldValues',
        'number_of_devices' => 'getNumberOfDevices',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PAYMENT_TYPE_CASH_ORDER = 'CashOrder';
    public const PAYMENT_TYPE_WIRE_TRANSFER = 'WireTransfer';
    public const PAYMENT_TYPE_SEPA_DIRECT_DEBIT_CORE = 'SepaDirectDebitCore';
    public const PAYMENT_TYPE_PAY_PAL = 'PayPal';
    public const PAYMENT_TYPE_STRIPE = 'Stripe';
    public const PAYMENT_TERM_PAYMENT_TERM30_E = 'PaymentTerm30E';
    public const PAYMENT_TERM_PAYMENT_TERM30_NE = 'PaymentTerm30NE';
    public const PAYMENT_TERM_PAYMENT_TERM45_E = 'PaymentTerm45E';
    public const PAYMENT_TERM_PAYMENT_TERM45_NE = 'PaymentTerm45NE';
    public const PAYMENT_TERM_PAYMENT_TERM60_E = 'PaymentTerm60E';
    public const PAYMENT_TERM_PAYMENT_TERM60_NE = 'PaymentTerm60NE';
    public const PAYMENT_TERM_PAYMENT_TERM90_E = 'PaymentTerm90E';
    public const PAYMENT_TERM_PAYMENT_TERM90_NE = 'PaymentTerm90NE';
    public const PAYMENT_TERM_PAYMENT_TERM120_E = 'PaymentTerm120E';
    public const PAYMENT_TERM_PAYMENT_TERM120_NE = 'PaymentTerm120NE';
    public const PAYMENT_TERM_PAYMENT_TERM60_E10 = 'PaymentTerm60E10';
    public const PAYMENT_TERM_PAYMENT_TERM30_E10 = 'PaymentTerm30E10';
    public const PAYMENT_TERM_PAYMENT_TERM_RF = 'PaymentTermRF';
    public const PAYMENT_TERM_PAYMENT_TERM90_E10 = 'PaymentTerm90E10';
    public const PAYMENT_TERM_PAYMENT_TERM7_NE = 'PaymentTerm7NE';
    public const PAYMENT_TERM_PAYMENT_TERM14_NE = 'PaymentTerm14NE';
    public const LANGUAGE_ITALIANO = 'Italiano';
    public const LANGUAGE_ENGLISH = 'English';
    public const LANGUAGE_DEUTSCHE = 'Deutsche';
    public const LANGUAGE_FRENCH = 'French';
    public const LANGUAGE_SPANISH = 'Spanish';
    public const LANGUAGE_NORWEGIAN = 'Norwegian';
    public const LANGUAGE_KOREAN = 'Korean';
    public const LANGUAGE_PORTUGUESE = 'Portuguese';
    public const LANGUAGE_CATALAN = 'Catalan';
    public const LANGUAGE_JAPANESE = 'Japanese';
    public const LANGUAGE_VIETNAMESE = 'Vietnamese';
    public const LANGUAGE_THAI = 'Thai';
    public const LANGUAGE_TRADITIONAL_CHINESE = 'TraditionalChinese';
    public const LANGUAGE_POLISH = 'Polish';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentTypeAllowableValues()
    {
        return [
            self::PAYMENT_TYPE_CASH_ORDER,
            self::PAYMENT_TYPE_WIRE_TRANSFER,
            self::PAYMENT_TYPE_SEPA_DIRECT_DEBIT_CORE,
            self::PAYMENT_TYPE_PAY_PAL,
            self::PAYMENT_TYPE_STRIPE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentTermAllowableValues()
    {
        return [
            self::PAYMENT_TERM_PAYMENT_TERM30_E,
            self::PAYMENT_TERM_PAYMENT_TERM30_NE,
            self::PAYMENT_TERM_PAYMENT_TERM45_E,
            self::PAYMENT_TERM_PAYMENT_TERM45_NE,
            self::PAYMENT_TERM_PAYMENT_TERM60_E,
            self::PAYMENT_TERM_PAYMENT_TERM60_NE,
            self::PAYMENT_TERM_PAYMENT_TERM90_E,
            self::PAYMENT_TERM_PAYMENT_TERM90_NE,
            self::PAYMENT_TERM_PAYMENT_TERM120_E,
            self::PAYMENT_TERM_PAYMENT_TERM120_NE,
            self::PAYMENT_TERM_PAYMENT_TERM60_E10,
            self::PAYMENT_TERM_PAYMENT_TERM30_E10,
            self::PAYMENT_TERM_PAYMENT_TERM_RF,
            self::PAYMENT_TERM_PAYMENT_TERM90_E10,
            self::PAYMENT_TERM_PAYMENT_TERM7_NE,
            self::PAYMENT_TERM_PAYMENT_TERM14_NE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLanguageAllowableValues()
    {
        return [
            self::LANGUAGE_ITALIANO,
            self::LANGUAGE_ENGLISH,
            self::LANGUAGE_DEUTSCHE,
            self::LANGUAGE_FRENCH,
            self::LANGUAGE_SPANISH,
            self::LANGUAGE_NORWEGIAN,
            self::LANGUAGE_KOREAN,
            self::LANGUAGE_PORTUGUESE,
            self::LANGUAGE_CATALAN,
            self::LANGUAGE_JAPANESE,
            self::LANGUAGE_VIETNAMESE,
            self::LANGUAGE_THAI,
            self::LANGUAGE_TRADITIONAL_CHINESE,
            self::LANGUAGE_POLISH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('is_billing', $data ?? [], null);
        $this->setIfExists('has_proforma', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('recipient', $data ?? [], null);
        $this->setIfExists('recipient_customer', $data ?? [], null);
        $this->setIfExists('bill_to', $data ?? [], null);
        $this->setIfExists('invoice_template', $data ?? [], null);
        $this->setIfExists('invoice_media_types', $data ?? [], null);
        $this->setIfExists('day_of_month', $data ?? [], null);
        $this->setIfExists('months', $data ?? [], null);
        $this->setIfExists('hour', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('email_proforma', $data ?? [], null);
        $this->setIfExists('is_mail_to_send', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('subject_proforma', $data ?? [], null);
        $this->setIfExists('invoice_heading', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('body_proforma', $data ?? [], null);
        $this->setIfExists('payment_type', $data ?? [], null);
        $this->setIfExists('payment_term', $data ?? [], null);
        $this->setIfExists('financial_discount_rate', $data ?? [], null);
        $this->setIfExists('tax_rate_code', $data ?? [], null);
        $this->setIfExists('is_dealer_tax_rate', $data ?? [], null);
        $this->setIfExists('tax_rate_reason', $data ?? [], null);
        $this->setIfExists('tax_rate_reason_type', $data ?? [], null);
        $this->setIfExists('tax_rate_reason_text_reference', $data ?? [], null);
        $this->setIfExists('tax_rate_reason_date_reference', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('sales_agent', $data ?? [], null);
        $this->setIfExists('issuer_bank', $data ?? [], null);
        $this->setIfExists('contract_billable_services', $data ?? [], null);
        $this->setIfExists('custom_field_values', $data ?? [], null);
        $this->setIfExists('number_of_devices', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPaymentTypeAllowableValues();
        if (!is_null($this->container['payment_type']) && !in_array($this->container['payment_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_type', must be one of '%s'",
                $this->container['payment_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPaymentTermAllowableValues();
        if (!is_null($this->container['payment_term']) && !in_array($this->container['payment_term'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_term', must be one of '%s'",
                $this->container['payment_term'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLanguageAllowableValues();
        if (!is_null($this->container['language']) && !in_array($this->container['language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'language', must be one of '%s'",
                $this->container['language'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_billing
     *
     * @return bool|null
     */
    public function getIsBilling()
    {
        return $this->container['is_billing'];
    }

    /**
     * Sets is_billing
     *
     * @param bool|null $is_billing True if it will produce only real invoices, False if it will produce only proforma invoices
     *
     * @return self
     */
    public function setIsBilling($is_billing)
    {
        if (is_null($is_billing)) {
            throw new \InvalidArgumentException('non-nullable is_billing cannot be null');
        }
        $this->container['is_billing'] = $is_billing;

        return $this;
    }

    /**
     * Gets has_proforma
     *
     * @return bool|null
     */
    public function getHasProforma()
    {
        return $this->container['has_proforma'];
    }

    /**
     * Sets has_proforma
     *
     * @param bool|null $has_proforma True if the real invoice will also have a proforma
     *
     * @return self
     */
    public function setHasProforma($has_proforma)
    {
        if (is_null($has_proforma)) {
            throw new \InvalidArgumentException('non-nullable has_proforma cannot be null');
        }
        $this->container['has_proforma'] = $has_proforma;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool|null $is_active True if the Billing Driver is active, that is it will produce invoices
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return \OpenAPI\Client\Model\DealerDto|null
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param \OpenAPI\Client\Model\DealerDto|null $issuer issuer
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return \OpenAPI\Client\Model\DealerDto|null
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param \OpenAPI\Client\Model\DealerDto|null $recipient recipient
     *
     * @return self
     */
    public function setRecipient($recipient)
    {
        if (is_null($recipient)) {
            throw new \InvalidArgumentException('non-nullable recipient cannot be null');
        }
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets recipient_customer
     *
     * @return \OpenAPI\Client\Model\CustomerDto|null
     */
    public function getRecipientCustomer()
    {
        return $this->container['recipient_customer'];
    }

    /**
     * Sets recipient_customer
     *
     * @param \OpenAPI\Client\Model\CustomerDto|null $recipient_customer recipient_customer
     *
     * @return self
     */
    public function setRecipientCustomer($recipient_customer)
    {
        if (is_null($recipient_customer)) {
            throw new \InvalidArgumentException('non-nullable recipient_customer cannot be null');
        }
        $this->container['recipient_customer'] = $recipient_customer;

        return $this;
    }

    /**
     * Gets bill_to
     *
     * @return \OpenAPI\Client\Model\CompanyDto|null
     */
    public function getBillTo()
    {
        return $this->container['bill_to'];
    }

    /**
     * Sets bill_to
     *
     * @param \OpenAPI\Client\Model\CompanyDto|null $bill_to bill_to
     *
     * @return self
     */
    public function setBillTo($bill_to)
    {
        if (is_null($bill_to)) {
            throw new \InvalidArgumentException('non-nullable bill_to cannot be null');
        }
        $this->container['bill_to'] = $bill_to;

        return $this;
    }

    /**
     * Gets invoice_template
     *
     * @return string|null
     */
    public function getInvoiceTemplate()
    {
        return $this->container['invoice_template'];
    }

    /**
     * Sets invoice_template
     *
     * @param string|null $invoice_template The invoice template
     *
     * @return self
     */
    public function setInvoiceTemplate($invoice_template)
    {
        if (is_null($invoice_template)) {
            throw new \InvalidArgumentException('non-nullable invoice_template cannot be null');
        }
        $this->container['invoice_template'] = $invoice_template;

        return $this;
    }

    /**
     * Gets invoice_media_types
     *
     * @return string|null
     */
    public function getInvoiceMediaTypes()
    {
        return $this->container['invoice_media_types'];
    }

    /**
     * Sets invoice_media_types
     *
     * @param string|null $invoice_media_types The invoice media types (pdf, xls, ...)
     *
     * @return self
     */
    public function setInvoiceMediaTypes($invoice_media_types)
    {
        if (is_null($invoice_media_types)) {
            throw new \InvalidArgumentException('non-nullable invoice_media_types cannot be null');
        }
        $this->container['invoice_media_types'] = $invoice_media_types;

        return $this;
    }

    /**
     * Gets day_of_month
     *
     * @return int|null
     */
    public function getDayOfMonth()
    {
        return $this->container['day_of_month'];
    }

    /**
     * Sets day_of_month
     *
     * @param int|null $day_of_month The day of month when the invoice will be generated
     *
     * @return self
     */
    public function setDayOfMonth($day_of_month)
    {
        if (is_null($day_of_month)) {
            throw new \InvalidArgumentException('non-nullable day_of_month cannot be null');
        }
        $this->container['day_of_month'] = $day_of_month;

        return $this;
    }

    /**
     * Gets months
     *
     * @return string|null
     */
    public function getMonths()
    {
        return $this->container['months'];
    }

    /**
     * Sets months
     *
     * @param string|null $months The months when the invoice will be generated
     *
     * @return self
     */
    public function setMonths($months)
    {
        if (is_null($months)) {
            throw new \InvalidArgumentException('non-nullable months cannot be null');
        }
        $this->container['months'] = $months;

        return $this;
    }

    /**
     * Gets hour
     *
     * @return int|null
     */
    public function getHour()
    {
        return $this->container['hour'];
    }

    /**
     * Sets hour
     *
     * @param int|null $hour The hour when the invoice will be generated
     *
     * @return self
     */
    public function setHour($hour)
    {
        if (is_null($hour)) {
            throw new \InvalidArgumentException('non-nullable hour cannot be null');
        }
        $this->container['hour'] = $hour;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The email where the invoice will be sent
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets email_proforma
     *
     * @return string|null
     */
    public function getEmailProforma()
    {
        return $this->container['email_proforma'];
    }

    /**
     * Sets email_proforma
     *
     * @param string|null $email_proforma The email where the proforma will be sent, in addition to dealers account emails
     *
     * @return self
     */
    public function setEmailProforma($email_proforma)
    {
        if (is_null($email_proforma)) {
            throw new \InvalidArgumentException('non-nullable email_proforma cannot be null');
        }
        $this->container['email_proforma'] = $email_proforma;

        return $this;
    }

    /**
     * Gets is_mail_to_send
     *
     * @return bool|null
     */
    public function getIsMailToSend()
    {
        return $this->container['is_mail_to_send'];
    }

    /**
     * Sets is_mail_to_send
     *
     * @param bool|null $is_mail_to_send True if the invoice will be sent to email
     *
     * @return self
     */
    public function setIsMailToSend($is_mail_to_send)
    {
        if (is_null($is_mail_to_send)) {
            throw new \InvalidArgumentException('non-nullable is_mail_to_send cannot be null');
        }
        $this->container['is_mail_to_send'] = $is_mail_to_send;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject The email subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets subject_proforma
     *
     * @return string|null
     */
    public function getSubjectProforma()
    {
        return $this->container['subject_proforma'];
    }

    /**
     * Sets subject_proforma
     *
     * @param string|null $subject_proforma The proforma subject
     *
     * @return self
     */
    public function setSubjectProforma($subject_proforma)
    {
        if (is_null($subject_proforma)) {
            throw new \InvalidArgumentException('non-nullable subject_proforma cannot be null');
        }
        $this->container['subject_proforma'] = $subject_proforma;

        return $this;
    }

    /**
     * Gets invoice_heading
     *
     * @return string|null
     */
    public function getInvoiceHeading()
    {
        return $this->container['invoice_heading'];
    }

    /**
     * Sets invoice_heading
     *
     * @param string|null $invoice_heading The invoice description
     *
     * @return self
     */
    public function setInvoiceHeading($invoice_heading)
    {
        if (is_null($invoice_heading)) {
            throw new \InvalidArgumentException('non-nullable invoice_heading cannot be null');
        }
        $this->container['invoice_heading'] = $invoice_heading;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string|null
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string|null $body The invoice email body
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets body_proforma
     *
     * @return string|null
     */
    public function getBodyProforma()
    {
        return $this->container['body_proforma'];
    }

    /**
     * Sets body_proforma
     *
     * @param string|null $body_proforma The proforma email body
     *
     * @return self
     */
    public function setBodyProforma($body_proforma)
    {
        if (is_null($body_proforma)) {
            throw new \InvalidArgumentException('non-nullable body_proforma cannot be null');
        }
        $this->container['body_proforma'] = $body_proforma;

        return $this;
    }

    /**
     * Gets payment_type
     *
     * @return string|null
     */
    public function getPaymentType()
    {
        return $this->container['payment_type'];
    }

    /**
     * Sets payment_type
     *
     * @param string|null $payment_type The invoice Payment Type
     *
     * @return self
     */
    public function setPaymentType($payment_type)
    {
        if (is_null($payment_type)) {
            throw new \InvalidArgumentException('non-nullable payment_type cannot be null');
        }
        $allowedValues = $this->getPaymentTypeAllowableValues();
        if (!in_array($payment_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_type', must be one of '%s'",
                    $payment_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_type'] = $payment_type;

        return $this;
    }

    /**
     * Gets payment_term
     *
     * @return string|null
     */
    public function getPaymentTerm()
    {
        return $this->container['payment_term'];
    }

    /**
     * Sets payment_term
     *
     * @param string|null $payment_term The invoice Payment Term
     *
     * @return self
     */
    public function setPaymentTerm($payment_term)
    {
        if (is_null($payment_term)) {
            throw new \InvalidArgumentException('non-nullable payment_term cannot be null');
        }
        $allowedValues = $this->getPaymentTermAllowableValues();
        if (!in_array($payment_term, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_term', must be one of '%s'",
                    $payment_term,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_term'] = $payment_term;

        return $this;
    }

    /**
     * Gets financial_discount_rate
     *
     * @return float|null
     */
    public function getFinancialDiscountRate()
    {
        return $this->container['financial_discount_rate'];
    }

    /**
     * Sets financial_discount_rate
     *
     * @param float|null $financial_discount_rate Financial Discount Rate
     *
     * @return self
     */
    public function setFinancialDiscountRate($financial_discount_rate)
    {
        if (is_null($financial_discount_rate)) {
            throw new \InvalidArgumentException('non-nullable financial_discount_rate cannot be null');
        }
        $this->container['financial_discount_rate'] = $financial_discount_rate;

        return $this;
    }

    /**
     * Gets tax_rate_code
     *
     * @return string|null
     */
    public function getTaxRateCode()
    {
        return $this->container['tax_rate_code'];
    }

    /**
     * Sets tax_rate_code
     *
     * @param string|null $tax_rate_code Tax Rate Code
     *
     * @return self
     */
    public function setTaxRateCode($tax_rate_code)
    {
        if (is_null($tax_rate_code)) {
            throw new \InvalidArgumentException('non-nullable tax_rate_code cannot be null');
        }
        $this->container['tax_rate_code'] = $tax_rate_code;

        return $this;
    }

    /**
     * Gets is_dealer_tax_rate
     *
     * @return bool|null
     */
    public function getIsDealerTaxRate()
    {
        return $this->container['is_dealer_tax_rate'];
    }

    /**
     * Sets is_dealer_tax_rate
     *
     * @param bool|null $is_dealer_tax_rate True if the Tax Rate Code refers to a Dealer Tax Rate Code
     *
     * @return self
     */
    public function setIsDealerTaxRate($is_dealer_tax_rate)
    {
        if (is_null($is_dealer_tax_rate)) {
            throw new \InvalidArgumentException('non-nullable is_dealer_tax_rate cannot be null');
        }
        $this->container['is_dealer_tax_rate'] = $is_dealer_tax_rate;

        return $this;
    }

    /**
     * Gets tax_rate_reason
     *
     * @return string|null
     */
    public function getTaxRateReason()
    {
        return $this->container['tax_rate_reason'];
    }

    /**
     * Sets tax_rate_reason
     *
     * @param string|null $tax_rate_reason Tax Rate Reason
     *
     * @return self
     */
    public function setTaxRateReason($tax_rate_reason)
    {
        if (is_null($tax_rate_reason)) {
            throw new \InvalidArgumentException('non-nullable tax_rate_reason cannot be null');
        }
        $this->container['tax_rate_reason'] = $tax_rate_reason;

        return $this;
    }

    /**
     * Gets tax_rate_reason_type
     *
     * @return string|null
     */
    public function getTaxRateReasonType()
    {
        return $this->container['tax_rate_reason_type'];
    }

    /**
     * Sets tax_rate_reason_type
     *
     * @param string|null $tax_rate_reason_type Tax Rate Reason Type
     *
     * @return self
     */
    public function setTaxRateReasonType($tax_rate_reason_type)
    {
        if (is_null($tax_rate_reason_type)) {
            throw new \InvalidArgumentException('non-nullable tax_rate_reason_type cannot be null');
        }
        $this->container['tax_rate_reason_type'] = $tax_rate_reason_type;

        return $this;
    }

    /**
     * Gets tax_rate_reason_text_reference
     *
     * @return string|null
     */
    public function getTaxRateReasonTextReference()
    {
        return $this->container['tax_rate_reason_text_reference'];
    }

    /**
     * Sets tax_rate_reason_text_reference
     *
     * @param string|null $tax_rate_reason_text_reference Tax Rate Reason Text Reference
     *
     * @return self
     */
    public function setTaxRateReasonTextReference($tax_rate_reason_text_reference)
    {
        if (is_null($tax_rate_reason_text_reference)) {
            throw new \InvalidArgumentException('non-nullable tax_rate_reason_text_reference cannot be null');
        }
        $this->container['tax_rate_reason_text_reference'] = $tax_rate_reason_text_reference;

        return $this;
    }

    /**
     * Gets tax_rate_reason_date_reference
     *
     * @return \DateTime|null
     */
    public function getTaxRateReasonDateReference()
    {
        return $this->container['tax_rate_reason_date_reference'];
    }

    /**
     * Sets tax_rate_reason_date_reference
     *
     * @param \DateTime|null $tax_rate_reason_date_reference Tax Rate Reason Date Reference
     *
     * @return self
     */
    public function setTaxRateReasonDateReference($tax_rate_reason_date_reference)
    {
        if (is_null($tax_rate_reason_date_reference)) {
            throw new \InvalidArgumentException('non-nullable tax_rate_reason_date_reference cannot be null');
        }
        $this->container['tax_rate_reason_date_reference'] = $tax_rate_reason_date_reference;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language The invoice language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $allowedValues = $this->getLanguageAllowableValues();
        if (!in_array($language, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'language', must be one of '%s'",
                    $language,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \OpenAPI\Client\Model\CurrencyDto|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \OpenAPI\Client\Model\CurrencyDto|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets sales_agent
     *
     * @return \OpenAPI\Client\Model\AccountDto|null
     */
    public function getSalesAgent()
    {
        return $this->container['sales_agent'];
    }

    /**
     * Sets sales_agent
     *
     * @param \OpenAPI\Client\Model\AccountDto|null $sales_agent sales_agent
     *
     * @return self
     */
    public function setSalesAgent($sales_agent)
    {
        if (is_null($sales_agent)) {
            throw new \InvalidArgumentException('non-nullable sales_agent cannot be null');
        }
        $this->container['sales_agent'] = $sales_agent;

        return $this;
    }

    /**
     * Gets issuer_bank
     *
     * @return \OpenAPI\Client\Model\DealerBankAccountDto|null
     */
    public function getIssuerBank()
    {
        return $this->container['issuer_bank'];
    }

    /**
     * Sets issuer_bank
     *
     * @param \OpenAPI\Client\Model\DealerBankAccountDto|null $issuer_bank issuer_bank
     *
     * @return self
     */
    public function setIssuerBank($issuer_bank)
    {
        if (is_null($issuer_bank)) {
            throw new \InvalidArgumentException('non-nullable issuer_bank cannot be null');
        }
        $this->container['issuer_bank'] = $issuer_bank;

        return $this;
    }

    /**
     * Gets contract_billable_services
     *
     * @return \OpenAPI\Client\Model\ContractBillableServiceDto[]|null
     */
    public function getContractBillableServices()
    {
        return $this->container['contract_billable_services'];
    }

    /**
     * Sets contract_billable_services
     *
     * @param \OpenAPI\Client\Model\ContractBillableServiceDto[]|null $contract_billable_services The Contract Billable Services list
     *
     * @return self
     */
    public function setContractBillableServices($contract_billable_services)
    {
        if (is_null($contract_billable_services)) {
            throw new \InvalidArgumentException('non-nullable contract_billable_services cannot be null');
        }
        $this->container['contract_billable_services'] = $contract_billable_services;

        return $this;
    }

    /**
     * Gets custom_field_values
     *
     * @return \OpenAPI\Client\Model\CustomFieldValueDto[]|null
     */
    public function getCustomFieldValues()
    {
        return $this->container['custom_field_values'];
    }

    /**
     * Sets custom_field_values
     *
     * @param \OpenAPI\Client\Model\CustomFieldValueDto[]|null $custom_field_values Gets or sets the custom fields
     *
     * @return self
     */
    public function setCustomFieldValues($custom_field_values)
    {
        if (is_null($custom_field_values)) {
            throw new \InvalidArgumentException('non-nullable custom_field_values cannot be null');
        }
        $this->container['custom_field_values'] = $custom_field_values;

        return $this;
    }

    /**
     * Gets number_of_devices
     *
     * @return int|null
     */
    public function getNumberOfDevices()
    {
        return $this->container['number_of_devices'];
    }

    /**
     * Sets number_of_devices
     *
     * @param int|null $number_of_devices Number of devices
     *
     * @return self
     */
    public function setNumberOfDevices($number_of_devices)
    {
        if (is_null($number_of_devices)) {
            throw new \InvalidArgumentException('non-nullable number_of_devices cannot be null');
        }
        $this->container['number_of_devices'] = $number_of_devices;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Gets or sets the identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


