<?php
/**
 * CustomerServicesStatusDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomerServicesStatusDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerServicesStatusDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomerServicesStatusDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'printreleaf_active' => 'bool',
        'can_activate_printreleaf' => 'bool',
        'hp_sds_active' => 'bool',
        'can_activate_hp_sds' => 'bool',
        'can_activate_paper_cut' => 'bool',
        'paper_cut_active' => 'bool',
        'remote_ws_active' => 'bool',
        'can_activate_sharp_fss' => 'bool',
        'sharp_fss_active' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'printreleaf_active' => null,
        'can_activate_printreleaf' => null,
        'hp_sds_active' => null,
        'can_activate_hp_sds' => null,
        'can_activate_paper_cut' => null,
        'paper_cut_active' => null,
        'remote_ws_active' => null,
        'can_activate_sharp_fss' => null,
        'sharp_fss_active' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'printreleaf_active' => false,
        'can_activate_printreleaf' => false,
        'hp_sds_active' => false,
        'can_activate_hp_sds' => false,
        'can_activate_paper_cut' => false,
        'paper_cut_active' => false,
        'remote_ws_active' => false,
        'can_activate_sharp_fss' => false,
        'sharp_fss_active' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'printreleaf_active' => 'PrintreleafActive',
        'can_activate_printreleaf' => 'CanActivatePrintreleaf',
        'hp_sds_active' => 'HpSdsActive',
        'can_activate_hp_sds' => 'CanActivateHpSds',
        'can_activate_paper_cut' => 'CanActivatePaperCut',
        'paper_cut_active' => 'PaperCutActive',
        'remote_ws_active' => 'RemoteWsActive',
        'can_activate_sharp_fss' => 'CanActivateSharpFSS',
        'sharp_fss_active' => 'SharpFSSActive'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'printreleaf_active' => 'setPrintreleafActive',
        'can_activate_printreleaf' => 'setCanActivatePrintreleaf',
        'hp_sds_active' => 'setHpSdsActive',
        'can_activate_hp_sds' => 'setCanActivateHpSds',
        'can_activate_paper_cut' => 'setCanActivatePaperCut',
        'paper_cut_active' => 'setPaperCutActive',
        'remote_ws_active' => 'setRemoteWsActive',
        'can_activate_sharp_fss' => 'setCanActivateSharpFss',
        'sharp_fss_active' => 'setSharpFssActive'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'printreleaf_active' => 'getPrintreleafActive',
        'can_activate_printreleaf' => 'getCanActivatePrintreleaf',
        'hp_sds_active' => 'getHpSdsActive',
        'can_activate_hp_sds' => 'getCanActivateHpSds',
        'can_activate_paper_cut' => 'getCanActivatePaperCut',
        'paper_cut_active' => 'getPaperCutActive',
        'remote_ws_active' => 'getRemoteWsActive',
        'can_activate_sharp_fss' => 'getCanActivateSharpFss',
        'sharp_fss_active' => 'getSharpFssActive'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('printreleaf_active', $data ?? [], null);
        $this->setIfExists('can_activate_printreleaf', $data ?? [], null);
        $this->setIfExists('hp_sds_active', $data ?? [], null);
        $this->setIfExists('can_activate_hp_sds', $data ?? [], null);
        $this->setIfExists('can_activate_paper_cut', $data ?? [], null);
        $this->setIfExists('paper_cut_active', $data ?? [], null);
        $this->setIfExists('remote_ws_active', $data ?? [], null);
        $this->setIfExists('can_activate_sharp_fss', $data ?? [], null);
        $this->setIfExists('sharp_fss_active', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets printreleaf_active
     *
     * @return bool|null
     */
    public function getPrintreleafActive()
    {
        return $this->container['printreleaf_active'];
    }

    /**
     * Sets printreleaf_active
     *
     * @param bool|null $printreleaf_active Gets or sets a value indicating whether [printreleaf active].
     *
     * @return self
     */
    public function setPrintreleafActive($printreleaf_active)
    {
        if (is_null($printreleaf_active)) {
            throw new \InvalidArgumentException('non-nullable printreleaf_active cannot be null');
        }
        $this->container['printreleaf_active'] = $printreleaf_active;

        return $this;
    }

    /**
     * Gets can_activate_printreleaf
     *
     * @return bool|null
     */
    public function getCanActivatePrintreleaf()
    {
        return $this->container['can_activate_printreleaf'];
    }

    /**
     * Sets can_activate_printreleaf
     *
     * @param bool|null $can_activate_printreleaf Gets or sets a value indicating whether this instance can activate printreleaf.
     *
     * @return self
     */
    public function setCanActivatePrintreleaf($can_activate_printreleaf)
    {
        if (is_null($can_activate_printreleaf)) {
            throw new \InvalidArgumentException('non-nullable can_activate_printreleaf cannot be null');
        }
        $this->container['can_activate_printreleaf'] = $can_activate_printreleaf;

        return $this;
    }

    /**
     * Gets hp_sds_active
     *
     * @return bool|null
     */
    public function getHpSdsActive()
    {
        return $this->container['hp_sds_active'];
    }

    /**
     * Sets hp_sds_active
     *
     * @param bool|null $hp_sds_active Gets or sets a value indicating whether [hp SDS active].
     *
     * @return self
     */
    public function setHpSdsActive($hp_sds_active)
    {
        if (is_null($hp_sds_active)) {
            throw new \InvalidArgumentException('non-nullable hp_sds_active cannot be null');
        }
        $this->container['hp_sds_active'] = $hp_sds_active;

        return $this;
    }

    /**
     * Gets can_activate_hp_sds
     *
     * @return bool|null
     */
    public function getCanActivateHpSds()
    {
        return $this->container['can_activate_hp_sds'];
    }

    /**
     * Sets can_activate_hp_sds
     *
     * @param bool|null $can_activate_hp_sds Gets or sets a value indicating whether this instance can activate hp SDS.
     *
     * @return self
     */
    public function setCanActivateHpSds($can_activate_hp_sds)
    {
        if (is_null($can_activate_hp_sds)) {
            throw new \InvalidArgumentException('non-nullable can_activate_hp_sds cannot be null');
        }
        $this->container['can_activate_hp_sds'] = $can_activate_hp_sds;

        return $this;
    }

    /**
     * Gets can_activate_paper_cut
     *
     * @return bool|null
     */
    public function getCanActivatePaperCut()
    {
        return $this->container['can_activate_paper_cut'];
    }

    /**
     * Sets can_activate_paper_cut
     *
     * @param bool|null $can_activate_paper_cut Gets or sets a value indicating whether this instance can activate paper cut.
     *
     * @return self
     */
    public function setCanActivatePaperCut($can_activate_paper_cut)
    {
        if (is_null($can_activate_paper_cut)) {
            throw new \InvalidArgumentException('non-nullable can_activate_paper_cut cannot be null');
        }
        $this->container['can_activate_paper_cut'] = $can_activate_paper_cut;

        return $this;
    }

    /**
     * Gets paper_cut_active
     *
     * @return bool|null
     */
    public function getPaperCutActive()
    {
        return $this->container['paper_cut_active'];
    }

    /**
     * Sets paper_cut_active
     *
     * @param bool|null $paper_cut_active Gets or sets a value indicating whether [paper cut active].
     *
     * @return self
     */
    public function setPaperCutActive($paper_cut_active)
    {
        if (is_null($paper_cut_active)) {
            throw new \InvalidArgumentException('non-nullable paper_cut_active cannot be null');
        }
        $this->container['paper_cut_active'] = $paper_cut_active;

        return $this;
    }

    /**
     * Gets remote_ws_active
     *
     * @return bool|null
     */
    public function getRemoteWsActive()
    {
        return $this->container['remote_ws_active'];
    }

    /**
     * Sets remote_ws_active
     *
     * @param bool|null $remote_ws_active Gets or sets a value indicating whether [remote ws active].
     *
     * @return self
     */
    public function setRemoteWsActive($remote_ws_active)
    {
        if (is_null($remote_ws_active)) {
            throw new \InvalidArgumentException('non-nullable remote_ws_active cannot be null');
        }
        $this->container['remote_ws_active'] = $remote_ws_active;

        return $this;
    }

    /**
     * Gets can_activate_sharp_fss
     *
     * @return bool|null
     */
    public function getCanActivateSharpFss()
    {
        return $this->container['can_activate_sharp_fss'];
    }

    /**
     * Sets can_activate_sharp_fss
     *
     * @param bool|null $can_activate_sharp_fss Gets or sets a value indicating whether this instance can activate Sharp FSS.
     *
     * @return self
     */
    public function setCanActivateSharpFss($can_activate_sharp_fss)
    {
        if (is_null($can_activate_sharp_fss)) {
            throw new \InvalidArgumentException('non-nullable can_activate_sharp_fss cannot be null');
        }
        $this->container['can_activate_sharp_fss'] = $can_activate_sharp_fss;

        return $this;
    }

    /**
     * Gets sharp_fss_active
     *
     * @return bool|null
     */
    public function getSharpFssActive()
    {
        return $this->container['sharp_fss_active'];
    }

    /**
     * Sets sharp_fss_active
     *
     * @param bool|null $sharp_fss_active Gets or sets a value indicating whether [Sharp FSS active].
     *
     * @return self
     */
    public function setSharpFssActive($sharp_fss_active)
    {
        if (is_null($sharp_fss_active)) {
            throw new \InvalidArgumentException('non-nullable sharp_fss_active cannot be null');
        }
        $this->container['sharp_fss_active'] = $sharp_fss_active;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


