<?php
/**
 * GetCustomerWithMpsDetailsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetCustomerWithMpsDetailsRequest Class Doc Comment
 *
 * @category Class
 * @description GetCustomerWithMpsDetailsRequest
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetCustomerWithMpsDetailsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetCustomerWithMpsDetailsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dealer_id' => 'string',
        'active_customer_filter' => 'bool',
        'communication_status' => 'string',
        'sds_only' => 'bool',
        'tags' => 'string',
        'filter_text' => 'string',
        'page_number' => 'int',
        'page_rows' => 'int',
        'sort_column' => 'string',
        'sort_order' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dealer_id' => null,
        'active_customer_filter' => null,
        'communication_status' => null,
        'sds_only' => null,
        'tags' => null,
        'filter_text' => null,
        'page_number' => 'int32',
        'page_rows' => 'int32',
        'sort_column' => null,
        'sort_order' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dealer_id' => false,
        'active_customer_filter' => false,
        'communication_status' => false,
        'sds_only' => false,
        'tags' => false,
        'filter_text' => false,
        'page_number' => false,
        'page_rows' => false,
        'sort_column' => false,
        'sort_order' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dealer_id' => 'DealerId',
        'active_customer_filter' => 'ActiveCustomerFilter',
        'communication_status' => 'CommunicationStatus',
        'sds_only' => 'SDSOnly',
        'tags' => 'Tags',
        'filter_text' => 'FilterText',
        'page_number' => 'PageNumber',
        'page_rows' => 'PageRows',
        'sort_column' => 'SortColumn',
        'sort_order' => 'SortOrder'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dealer_id' => 'setDealerId',
        'active_customer_filter' => 'setActiveCustomerFilter',
        'communication_status' => 'setCommunicationStatus',
        'sds_only' => 'setSdsOnly',
        'tags' => 'setTags',
        'filter_text' => 'setFilterText',
        'page_number' => 'setPageNumber',
        'page_rows' => 'setPageRows',
        'sort_column' => 'setSortColumn',
        'sort_order' => 'setSortOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dealer_id' => 'getDealerId',
        'active_customer_filter' => 'getActiveCustomerFilter',
        'communication_status' => 'getCommunicationStatus',
        'sds_only' => 'getSdsOnly',
        'tags' => 'getTags',
        'filter_text' => 'getFilterText',
        'page_number' => 'getPageNumber',
        'page_rows' => 'getPageRows',
        'sort_column' => 'getSortColumn',
        'sort_order' => 'getSortOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const COMMUNICATION_STATUS_ALL = 'All';
    public const COMMUNICATION_STATUS_LAST_DAY = 'LastDay';
    public const COMMUNICATION_STATUS_LAST_PERIOD = 'LastPeriod';
    public const COMMUNICATION_STATUS_OVER_PERIOD = 'OverPeriod';
    public const SORT_ORDER_ASC = 'Asc';
    public const SORT_ORDER_DESC = 'Desc';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCommunicationStatusAllowableValues()
    {
        return [
            self::COMMUNICATION_STATUS_ALL,
            self::COMMUNICATION_STATUS_LAST_DAY,
            self::COMMUNICATION_STATUS_LAST_PERIOD,
            self::COMMUNICATION_STATUS_OVER_PERIOD,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSortOrderAllowableValues()
    {
        return [
            self::SORT_ORDER_ASC,
            self::SORT_ORDER_DESC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dealer_id', $data ?? [], null);
        $this->setIfExists('active_customer_filter', $data ?? [], null);
        $this->setIfExists('communication_status', $data ?? [], null);
        $this->setIfExists('sds_only', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('filter_text', $data ?? [], null);
        $this->setIfExists('page_number', $data ?? [], null);
        $this->setIfExists('page_rows', $data ?? [], null);
        $this->setIfExists('sort_column', $data ?? [], null);
        $this->setIfExists('sort_order', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCommunicationStatusAllowableValues();
        if (!is_null($this->container['communication_status']) && !in_array($this->container['communication_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'communication_status', must be one of '%s'",
                $this->container['communication_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['page_number'] === null) {
            $invalidProperties[] = "'page_number' can't be null";
        }
        if ($this->container['page_rows'] === null) {
            $invalidProperties[] = "'page_rows' can't be null";
        }
        if ($this->container['sort_column'] === null) {
            $invalidProperties[] = "'sort_column' can't be null";
        }
        if ($this->container['sort_order'] === null) {
            $invalidProperties[] = "'sort_order' can't be null";
        }
        $allowedValues = $this->getSortOrderAllowableValues();
        if (!is_null($this->container['sort_order']) && !in_array($this->container['sort_order'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sort_order', must be one of '%s'",
                $this->container['sort_order'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dealer_id
     *
     * @return string|null
     */
    public function getDealerId()
    {
        return $this->container['dealer_id'];
    }

    /**
     * Sets dealer_id
     *
     * @param string|null $dealer_id Gets or sets the dealer identifier.
     *
     * @return self
     */
    public function setDealerId($dealer_id)
    {
        if (is_null($dealer_id)) {
            throw new \InvalidArgumentException('non-nullable dealer_id cannot be null');
        }
        $this->container['dealer_id'] = $dealer_id;

        return $this;
    }

    /**
     * Gets active_customer_filter
     *
     * @return bool|null
     */
    public function getActiveCustomerFilter()
    {
        return $this->container['active_customer_filter'];
    }

    /**
     * Sets active_customer_filter
     *
     * @param bool|null $active_customer_filter Gets or sets the active customer filter.
     *
     * @return self
     */
    public function setActiveCustomerFilter($active_customer_filter)
    {
        if (is_null($active_customer_filter)) {
            throw new \InvalidArgumentException('non-nullable active_customer_filter cannot be null');
        }
        $this->container['active_customer_filter'] = $active_customer_filter;

        return $this;
    }

    /**
     * Gets communication_status
     *
     * @return string|null
     */
    public function getCommunicationStatus()
    {
        return $this->container['communication_status'];
    }

    /**
     * Sets communication_status
     *
     * @param string|null $communication_status Gets or sets the communication status.
     *
     * @return self
     */
    public function setCommunicationStatus($communication_status)
    {
        if (is_null($communication_status)) {
            throw new \InvalidArgumentException('non-nullable communication_status cannot be null');
        }
        $allowedValues = $this->getCommunicationStatusAllowableValues();
        if (!in_array($communication_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'communication_status', must be one of '%s'",
                    $communication_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['communication_status'] = $communication_status;

        return $this;
    }

    /**
     * Gets sds_only
     *
     * @return bool|null
     */
    public function getSdsOnly()
    {
        return $this->container['sds_only'];
    }

    /**
     * Sets sds_only
     *
     * @param bool|null $sds_only Gets or sets the filter jam.
     *
     * @return self
     */
    public function setSdsOnly($sds_only)
    {
        if (is_null($sds_only)) {
            throw new \InvalidArgumentException('non-nullable sds_only cannot be null');
        }
        $this->container['sds_only'] = $sds_only;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags Gets or sets the tags (separated by , ).
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets filter_text
     *
     * @return string|null
     */
    public function getFilterText()
    {
        return $this->container['filter_text'];
    }

    /**
     * Sets filter_text
     *
     * @param string|null $filter_text Gets or sets the filter text.
     *
     * @return self
     */
    public function setFilterText($filter_text)
    {
        if (is_null($filter_text)) {
            throw new \InvalidArgumentException('non-nullable filter_text cannot be null');
        }
        $this->container['filter_text'] = $filter_text;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int $page_number Gets or sets the page number.
     *
     * @return self
     */
    public function setPageNumber($page_number)
    {
        if (is_null($page_number)) {
            throw new \InvalidArgumentException('non-nullable page_number cannot be null');
        }
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets page_rows
     *
     * @return int
     */
    public function getPageRows()
    {
        return $this->container['page_rows'];
    }

    /**
     * Sets page_rows
     *
     * @param int $page_rows Gets or sets the page rows.
     *
     * @return self
     */
    public function setPageRows($page_rows)
    {
        if (is_null($page_rows)) {
            throw new \InvalidArgumentException('non-nullable page_rows cannot be null');
        }
        $this->container['page_rows'] = $page_rows;

        return $this;
    }

    /**
     * Gets sort_column
     *
     * @return string
     */
    public function getSortColumn()
    {
        return $this->container['sort_column'];
    }

    /**
     * Sets sort_column
     *
     * @param string $sort_column Gets or sets the sort column.
     *
     * @return self
     */
    public function setSortColumn($sort_column)
    {
        if (is_null($sort_column)) {
            throw new \InvalidArgumentException('non-nullable sort_column cannot be null');
        }
        $this->container['sort_column'] = $sort_column;

        return $this;
    }

    /**
     * Gets sort_order
     *
     * @return string
     */
    public function getSortOrder()
    {
        return $this->container['sort_order'];
    }

    /**
     * Sets sort_order
     *
     * @param string $sort_order Gets or sets the sort order.
     *
     * @return self
     */
    public function setSortOrder($sort_order)
    {
        if (is_null($sort_order)) {
            throw new \InvalidArgumentException('non-nullable sort_order cannot be null');
        }
        $allowedValues = $this->getSortOrderAllowableValues();
        if (!in_array($sort_order, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sort_order', must be one of '%s'",
                    $sort_order,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sort_order'] = $sort_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


