<?php
/**
 * OfficeListDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OfficeListDto Class Doc Comment
 *
 * @category Class
 * @description Represent an office
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OfficeListDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OfficeListDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'customer' => '\OpenAPI\Client\Model\CustomerBaseDto',
        'code' => 'string',
        'description' => 'string',
        'is_default' => 'bool',
        'destination_code' => 'string',
        'address' => 'string',
        'sap' => 'string',
        'telephone' => 'string',
        'fax' => 'string',
        'city' => 'string',
        'zip_code' => 'string',
        'province' => 'string',
        'country' => 'string',
        'id_country' => 'string',
        'is_country_eu' => 'bool',
        'lat' => 'float',
        'lng' => 'float',
        'mail_address' => 'string',
        'delivery_toner_mails' => 'string',
        'destination_description' => 'string',
        'enable_auto_assign' => 'bool',
        'note' => 'string',
        'customer_id' => 'string',
        'available_devices' => 'int',
        'office_subnets' => '\OpenAPI\Client\Model\OfficeSubnetDto[]',
        'external_identifier' => 'string',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'customer' => null,
        'code' => null,
        'description' => null,
        'is_default' => null,
        'destination_code' => null,
        'address' => null,
        'sap' => null,
        'telephone' => null,
        'fax' => null,
        'city' => null,
        'zip_code' => null,
        'province' => null,
        'country' => null,
        'id_country' => null,
        'is_country_eu' => null,
        'lat' => 'float',
        'lng' => 'float',
        'mail_address' => null,
        'delivery_toner_mails' => null,
        'destination_description' => null,
        'enable_auto_assign' => null,
        'note' => null,
        'customer_id' => null,
        'available_devices' => 'int32',
        'office_subnets' => null,
        'external_identifier' => null,
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'customer' => false,
        'code' => false,
        'description' => false,
        'is_default' => false,
        'destination_code' => false,
        'address' => false,
        'sap' => false,
        'telephone' => false,
        'fax' => false,
        'city' => false,
        'zip_code' => false,
        'province' => false,
        'country' => false,
        'id_country' => false,
        'is_country_eu' => false,
        'lat' => false,
        'lng' => false,
        'mail_address' => false,
        'delivery_toner_mails' => false,
        'destination_description' => false,
        'enable_auto_assign' => false,
        'note' => false,
        'customer_id' => false,
        'available_devices' => false,
        'office_subnets' => false,
        'external_identifier' => false,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customer' => 'Customer',
        'code' => 'Code',
        'description' => 'Description',
        'is_default' => 'IsDefault',
        'destination_code' => 'DestinationCode',
        'address' => 'Address',
        'sap' => 'Sap',
        'telephone' => 'Telephone',
        'fax' => 'Fax',
        'city' => 'City',
        'zip_code' => 'ZipCode',
        'province' => 'Province',
        'country' => 'Country',
        'id_country' => 'IdCountry',
        'is_country_eu' => 'IsCountryEu',
        'lat' => 'Lat',
        'lng' => 'Lng',
        'mail_address' => 'MailAddress',
        'delivery_toner_mails' => 'DeliveryTonerMails',
        'destination_description' => 'DestinationDescription',
        'enable_auto_assign' => 'EnableAutoAssign',
        'note' => 'Note',
        'customer_id' => 'CustomerId',
        'available_devices' => 'AvailableDevices',
        'office_subnets' => 'OfficeSubnets',
        'external_identifier' => 'ExternalIdentifier',
        'id' => 'Id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customer' => 'setCustomer',
        'code' => 'setCode',
        'description' => 'setDescription',
        'is_default' => 'setIsDefault',
        'destination_code' => 'setDestinationCode',
        'address' => 'setAddress',
        'sap' => 'setSap',
        'telephone' => 'setTelephone',
        'fax' => 'setFax',
        'city' => 'setCity',
        'zip_code' => 'setZipCode',
        'province' => 'setProvince',
        'country' => 'setCountry',
        'id_country' => 'setIdCountry',
        'is_country_eu' => 'setIsCountryEu',
        'lat' => 'setLat',
        'lng' => 'setLng',
        'mail_address' => 'setMailAddress',
        'delivery_toner_mails' => 'setDeliveryTonerMails',
        'destination_description' => 'setDestinationDescription',
        'enable_auto_assign' => 'setEnableAutoAssign',
        'note' => 'setNote',
        'customer_id' => 'setCustomerId',
        'available_devices' => 'setAvailableDevices',
        'office_subnets' => 'setOfficeSubnets',
        'external_identifier' => 'setExternalIdentifier',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customer' => 'getCustomer',
        'code' => 'getCode',
        'description' => 'getDescription',
        'is_default' => 'getIsDefault',
        'destination_code' => 'getDestinationCode',
        'address' => 'getAddress',
        'sap' => 'getSap',
        'telephone' => 'getTelephone',
        'fax' => 'getFax',
        'city' => 'getCity',
        'zip_code' => 'getZipCode',
        'province' => 'getProvince',
        'country' => 'getCountry',
        'id_country' => 'getIdCountry',
        'is_country_eu' => 'getIsCountryEu',
        'lat' => 'getLat',
        'lng' => 'getLng',
        'mail_address' => 'getMailAddress',
        'delivery_toner_mails' => 'getDeliveryTonerMails',
        'destination_description' => 'getDestinationDescription',
        'enable_auto_assign' => 'getEnableAutoAssign',
        'note' => 'getNote',
        'customer_id' => 'getCustomerId',
        'available_devices' => 'getAvailableDevices',
        'office_subnets' => 'getOfficeSubnets',
        'external_identifier' => 'getExternalIdentifier',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('is_default', $data ?? [], null);
        $this->setIfExists('destination_code', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('sap', $data ?? [], null);
        $this->setIfExists('telephone', $data ?? [], null);
        $this->setIfExists('fax', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('zip_code', $data ?? [], null);
        $this->setIfExists('province', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('id_country', $data ?? [], null);
        $this->setIfExists('is_country_eu', $data ?? [], null);
        $this->setIfExists('lat', $data ?? [], null);
        $this->setIfExists('lng', $data ?? [], null);
        $this->setIfExists('mail_address', $data ?? [], null);
        $this->setIfExists('delivery_toner_mails', $data ?? [], null);
        $this->setIfExists('destination_description', $data ?? [], null);
        $this->setIfExists('enable_auto_assign', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('available_devices', $data ?? [], null);
        $this->setIfExists('office_subnets', $data ?? [], null);
        $this->setIfExists('external_identifier', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customer
     *
     * @return \OpenAPI\Client\Model\CustomerBaseDto|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \OpenAPI\Client\Model\CustomerBaseDto|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Gets or sets the code.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Gets or sets the description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets is_default
     *
     * @return bool|null
     */
    public function getIsDefault()
    {
        return $this->container['is_default'];
    }

    /**
     * Sets is_default
     *
     * @param bool|null $is_default Gets or sets a value indicating whether this instance is default.
     *
     * @return self
     */
    public function setIsDefault($is_default)
    {
        if (is_null($is_default)) {
            throw new \InvalidArgumentException('non-nullable is_default cannot be null');
        }
        $this->container['is_default'] = $is_default;

        return $this;
    }

    /**
     * Gets destination_code
     *
     * @return string|null
     */
    public function getDestinationCode()
    {
        return $this->container['destination_code'];
    }

    /**
     * Sets destination_code
     *
     * @param string|null $destination_code Gets or sets the DestinationCode.
     *
     * @return self
     */
    public function setDestinationCode($destination_code)
    {
        if (is_null($destination_code)) {
            throw new \InvalidArgumentException('non-nullable destination_code cannot be null');
        }
        $this->container['destination_code'] = $destination_code;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address Gets or sets the address.
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets sap
     *
     * @return string|null
     */
    public function getSap()
    {
        return $this->container['sap'];
    }

    /**
     * Sets sap
     *
     * @param string|null $sap Gets or sets the Sap.
     *
     * @return self
     */
    public function setSap($sap)
    {
        if (is_null($sap)) {
            throw new \InvalidArgumentException('non-nullable sap cannot be null');
        }
        $this->container['sap'] = $sap;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string|null
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string|null $telephone Gets or sets the telephone.
     *
     * @return self
     */
    public function setTelephone($telephone)
    {
        if (is_null($telephone)) {
            throw new \InvalidArgumentException('non-nullable telephone cannot be null');
        }
        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string|null
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string|null $fax Gets or sets the fax.
     *
     * @return self
     */
    public function setFax($fax)
    {
        if (is_null($fax)) {
            throw new \InvalidArgumentException('non-nullable fax cannot be null');
        }
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city Gets or sets the city.
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets zip_code
     *
     * @return string|null
     */
    public function getZipCode()
    {
        return $this->container['zip_code'];
    }

    /**
     * Sets zip_code
     *
     * @param string|null $zip_code Gets or sets the zip code.
     *
     * @return self
     */
    public function setZipCode($zip_code)
    {
        if (is_null($zip_code)) {
            throw new \InvalidArgumentException('non-nullable zip_code cannot be null');
        }
        $this->container['zip_code'] = $zip_code;

        return $this;
    }

    /**
     * Gets province
     *
     * @return string|null
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     *
     * @param string|null $province Gets or sets the province.
     *
     * @return self
     */
    public function setProvince($province)
    {
        if (is_null($province)) {
            throw new \InvalidArgumentException('non-nullable province cannot be null');
        }
        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Gets or sets the Country.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets id_country
     *
     * @return string|null
     */
    public function getIdCountry()
    {
        return $this->container['id_country'];
    }

    /**
     * Sets id_country
     *
     * @param string|null $id_country Gets or sets the Country Id.
     *
     * @return self
     */
    public function setIdCountry($id_country)
    {
        if (is_null($id_country)) {
            throw new \InvalidArgumentException('non-nullable id_country cannot be null');
        }
        $this->container['id_country'] = $id_country;

        return $this;
    }

    /**
     * Gets is_country_eu
     *
     * @return bool|null
     */
    public function getIsCountryEu()
    {
        return $this->container['is_country_eu'];
    }

    /**
     * Sets is_country_eu
     *
     * @param bool|null $is_country_eu Gets or sets a value indicating whether this instance is country eu.
     *
     * @return self
     */
    public function setIsCountryEu($is_country_eu)
    {
        if (is_null($is_country_eu)) {
            throw new \InvalidArgumentException('non-nullable is_country_eu cannot be null');
        }
        $this->container['is_country_eu'] = $is_country_eu;

        return $this;
    }

    /**
     * Gets lat
     *
     * @return float|null
     */
    public function getLat()
    {
        return $this->container['lat'];
    }

    /**
     * Sets lat
     *
     * @param float|null $lat Gets or sets the latitude.
     *
     * @return self
     */
    public function setLat($lat)
    {
        if (is_null($lat)) {
            throw new \InvalidArgumentException('non-nullable lat cannot be null');
        }
        $this->container['lat'] = $lat;

        return $this;
    }

    /**
     * Gets lng
     *
     * @return float|null
     */
    public function getLng()
    {
        return $this->container['lng'];
    }

    /**
     * Sets lng
     *
     * @param float|null $lng Gets or sets the Longitute.
     *
     * @return self
     */
    public function setLng($lng)
    {
        if (is_null($lng)) {
            throw new \InvalidArgumentException('non-nullable lng cannot be null');
        }
        $this->container['lng'] = $lng;

        return $this;
    }

    /**
     * Gets mail_address
     *
     * @return string|null
     */
    public function getMailAddress()
    {
        return $this->container['mail_address'];
    }

    /**
     * Sets mail_address
     *
     * @param string|null $mail_address Gets or sets the mail address.
     *
     * @return self
     */
    public function setMailAddress($mail_address)
    {
        if (is_null($mail_address)) {
            throw new \InvalidArgumentException('non-nullable mail_address cannot be null');
        }
        $this->container['mail_address'] = $mail_address;

        return $this;
    }

    /**
     * Gets delivery_toner_mails
     *
     * @return string|null
     */
    public function getDeliveryTonerMails()
    {
        return $this->container['delivery_toner_mails'];
    }

    /**
     * Sets delivery_toner_mails
     *
     * @param string|null $delivery_toner_mails Gets or sets the DeliveryTonerMails.
     *
     * @return self
     */
    public function setDeliveryTonerMails($delivery_toner_mails)
    {
        if (is_null($delivery_toner_mails)) {
            throw new \InvalidArgumentException('non-nullable delivery_toner_mails cannot be null');
        }
        $this->container['delivery_toner_mails'] = $delivery_toner_mails;

        return $this;
    }

    /**
     * Gets destination_description
     *
     * @return string|null
     */
    public function getDestinationDescription()
    {
        return $this->container['destination_description'];
    }

    /**
     * Sets destination_description
     *
     * @param string|null $destination_description Gets or sets the destinationDescription.
     *
     * @return self
     */
    public function setDestinationDescription($destination_description)
    {
        if (is_null($destination_description)) {
            throw new \InvalidArgumentException('non-nullable destination_description cannot be null');
        }
        $this->container['destination_description'] = $destination_description;

        return $this;
    }

    /**
     * Gets enable_auto_assign
     *
     * @return bool|null
     */
    public function getEnableAutoAssign()
    {
        return $this->container['enable_auto_assign'];
    }

    /**
     * Sets enable_auto_assign
     *
     * @param bool|null $enable_auto_assign Gets or sets the EnableAutoAssign.
     *
     * @return self
     */
    public function setEnableAutoAssign($enable_auto_assign)
    {
        if (is_null($enable_auto_assign)) {
            throw new \InvalidArgumentException('non-nullable enable_auto_assign cannot be null');
        }
        $this->container['enable_auto_assign'] = $enable_auto_assign;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note Gets or sets the Note.
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id Gets or sets the customer identifier.
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            throw new \InvalidArgumentException('non-nullable customer_id cannot be null');
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets available_devices
     *
     * @return int|null
     */
    public function getAvailableDevices()
    {
        return $this->container['available_devices'];
    }

    /**
     * Sets available_devices
     *
     * @param int|null $available_devices Gets or sets the devices Numbers
     *
     * @return self
     */
    public function setAvailableDevices($available_devices)
    {
        if (is_null($available_devices)) {
            throw new \InvalidArgumentException('non-nullable available_devices cannot be null');
        }
        $this->container['available_devices'] = $available_devices;

        return $this;
    }

    /**
     * Gets office_subnets
     *
     * @return \OpenAPI\Client\Model\OfficeSubnetDto[]|null
     */
    public function getOfficeSubnets()
    {
        return $this->container['office_subnets'];
    }

    /**
     * Sets office_subnets
     *
     * @param \OpenAPI\Client\Model\OfficeSubnetDto[]|null $office_subnets Gets or sets the subnets
     *
     * @return self
     */
    public function setOfficeSubnets($office_subnets)
    {
        if (is_null($office_subnets)) {
            throw new \InvalidArgumentException('non-nullable office_subnets cannot be null');
        }
        $this->container['office_subnets'] = $office_subnets;

        return $this;
    }

    /**
     * Gets external_identifier
     *
     * @return string|null
     */
    public function getExternalIdentifier()
    {
        return $this->container['external_identifier'];
    }

    /**
     * Sets external_identifier
     *
     * @param string|null $external_identifier Gets or sets the external identifier.
     *
     * @return self
     */
    public function setExternalIdentifier($external_identifier)
    {
        if (is_null($external_identifier)) {
            throw new \InvalidArgumentException('non-nullable external_identifier cannot be null');
        }
        $this->container['external_identifier'] = $external_identifier;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Gets or sets the identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


