<?php
/**
 * PassiveInvoiceHeaderDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PassiveInvoiceHeaderDto Class Doc Comment
 *
 * @category Class
 * @description Represents a Passive Invoice
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PassiveInvoiceHeaderDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PassiveInvoiceHeaderDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'is_credit' => 'bool',
        'status' => 'string',
        'id_recipient' => 'string',
        'recipient_code' => 'string',
        'recipient_vat_number' => 'string',
        'recipient_description' => 'string',
        'issuer_company' => '\OpenAPI\Client\Model\CompanyDto',
        'issuer_vat_number' => 'string',
        'issuer_description' => 'string',
        'issuer_address' => 'string',
        'issuer_zip_code' => 'string',
        'issuer_city' => 'string',
        'issuer_province' => 'string',
        'issuer_country' => '\OpenAPI\Client\Model\CountryDto',
        'invoice_number' => 'string',
        'issue_date' => '\DateTime',
        'received_date' => '\DateTime',
        'invoice_heading' => 'string',
        'net_amount' => 'float',
        'tax' => 'float',
        'total' => 'float',
        'net_amount_currency' => 'float',
        'tax_currency' => 'float',
        'total_currency' => 'float',
        'is_to_pay' => 'bool',
        'is_paid' => 'bool',
        'payment_date' => '\DateTime',
        'currency' => '\OpenAPI\Client\Model\CurrencyDto',
        'invoice_category' => '\OpenAPI\Client\Model\InvoiceCategoryDto',
        'alternative_invoice_category' => '\OpenAPI\Client\Model\InvoiceCategoryDto',
        'sdi_document_type' => 'string',
        'attachments' => '\OpenAPI\Client\Model\PassiveInvoiceAttachmentDto[]',
        'uploaded_attachments' => '\OpenAPI\Client\Model\FileInfoDto[]',
        'passive_invoice_rows' => '\OpenAPI\Client\Model\PassiveInvoiceRowDto[]',
        'passive_invoice_payment_conditions' => '\OpenAPI\Client\Model\PassiveInvoicePaymentConditionDto[]',
        'issuer_info' => 'string',
        'recipient_info' => 'string',
        'id_passive_invoice' => 'int',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'is_credit' => null,
        'status' => null,
        'id_recipient' => null,
        'recipient_code' => null,
        'recipient_vat_number' => null,
        'recipient_description' => null,
        'issuer_company' => null,
        'issuer_vat_number' => null,
        'issuer_description' => null,
        'issuer_address' => null,
        'issuer_zip_code' => null,
        'issuer_city' => null,
        'issuer_province' => null,
        'issuer_country' => null,
        'invoice_number' => null,
        'issue_date' => 'date-time',
        'received_date' => 'date-time',
        'invoice_heading' => null,
        'net_amount' => 'double',
        'tax' => 'double',
        'total' => 'double',
        'net_amount_currency' => 'double',
        'tax_currency' => 'double',
        'total_currency' => 'double',
        'is_to_pay' => null,
        'is_paid' => null,
        'payment_date' => 'date-time',
        'currency' => null,
        'invoice_category' => null,
        'alternative_invoice_category' => null,
        'sdi_document_type' => null,
        'attachments' => null,
        'uploaded_attachments' => null,
        'passive_invoice_rows' => null,
        'passive_invoice_payment_conditions' => null,
        'issuer_info' => null,
        'recipient_info' => null,
        'id_passive_invoice' => 'int32',
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'is_credit' => false,
        'status' => false,
        'id_recipient' => false,
        'recipient_code' => false,
        'recipient_vat_number' => false,
        'recipient_description' => false,
        'issuer_company' => false,
        'issuer_vat_number' => false,
        'issuer_description' => false,
        'issuer_address' => false,
        'issuer_zip_code' => false,
        'issuer_city' => false,
        'issuer_province' => false,
        'issuer_country' => false,
        'invoice_number' => false,
        'issue_date' => false,
        'received_date' => false,
        'invoice_heading' => false,
        'net_amount' => false,
        'tax' => false,
        'total' => false,
        'net_amount_currency' => false,
        'tax_currency' => false,
        'total_currency' => false,
        'is_to_pay' => false,
        'is_paid' => false,
        'payment_date' => false,
        'currency' => false,
        'invoice_category' => false,
        'alternative_invoice_category' => false,
        'sdi_document_type' => false,
        'attachments' => false,
        'uploaded_attachments' => false,
        'passive_invoice_rows' => false,
        'passive_invoice_payment_conditions' => false,
        'issuer_info' => false,
        'recipient_info' => false,
        'id_passive_invoice' => false,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_credit' => 'IsCredit',
        'status' => 'Status',
        'id_recipient' => 'IdRecipient',
        'recipient_code' => 'RecipientCode',
        'recipient_vat_number' => 'RecipientVatNumber',
        'recipient_description' => 'RecipientDescription',
        'issuer_company' => 'IssuerCompany',
        'issuer_vat_number' => 'IssuerVatNumber',
        'issuer_description' => 'IssuerDescription',
        'issuer_address' => 'IssuerAddress',
        'issuer_zip_code' => 'IssuerZipCode',
        'issuer_city' => 'IssuerCity',
        'issuer_province' => 'IssuerProvince',
        'issuer_country' => 'IssuerCountry',
        'invoice_number' => 'InvoiceNumber',
        'issue_date' => 'IssueDate',
        'received_date' => 'ReceivedDate',
        'invoice_heading' => 'InvoiceHeading',
        'net_amount' => 'NetAmount',
        'tax' => 'Tax',
        'total' => 'Total',
        'net_amount_currency' => 'NetAmountCurrency',
        'tax_currency' => 'TaxCurrency',
        'total_currency' => 'TotalCurrency',
        'is_to_pay' => 'IsToPay',
        'is_paid' => 'IsPaid',
        'payment_date' => 'PaymentDate',
        'currency' => 'Currency',
        'invoice_category' => 'InvoiceCategory',
        'alternative_invoice_category' => 'AlternativeInvoiceCategory',
        'sdi_document_type' => 'SDIDocumentType',
        'attachments' => 'Attachments',
        'uploaded_attachments' => 'UploadedAttachments',
        'passive_invoice_rows' => 'PassiveInvoiceRows',
        'passive_invoice_payment_conditions' => 'PassiveInvoicePaymentConditions',
        'issuer_info' => 'IssuerInfo',
        'recipient_info' => 'RecipientInfo',
        'id_passive_invoice' => 'IdPassiveInvoice',
        'id' => 'Id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_credit' => 'setIsCredit',
        'status' => 'setStatus',
        'id_recipient' => 'setIdRecipient',
        'recipient_code' => 'setRecipientCode',
        'recipient_vat_number' => 'setRecipientVatNumber',
        'recipient_description' => 'setRecipientDescription',
        'issuer_company' => 'setIssuerCompany',
        'issuer_vat_number' => 'setIssuerVatNumber',
        'issuer_description' => 'setIssuerDescription',
        'issuer_address' => 'setIssuerAddress',
        'issuer_zip_code' => 'setIssuerZipCode',
        'issuer_city' => 'setIssuerCity',
        'issuer_province' => 'setIssuerProvince',
        'issuer_country' => 'setIssuerCountry',
        'invoice_number' => 'setInvoiceNumber',
        'issue_date' => 'setIssueDate',
        'received_date' => 'setReceivedDate',
        'invoice_heading' => 'setInvoiceHeading',
        'net_amount' => 'setNetAmount',
        'tax' => 'setTax',
        'total' => 'setTotal',
        'net_amount_currency' => 'setNetAmountCurrency',
        'tax_currency' => 'setTaxCurrency',
        'total_currency' => 'setTotalCurrency',
        'is_to_pay' => 'setIsToPay',
        'is_paid' => 'setIsPaid',
        'payment_date' => 'setPaymentDate',
        'currency' => 'setCurrency',
        'invoice_category' => 'setInvoiceCategory',
        'alternative_invoice_category' => 'setAlternativeInvoiceCategory',
        'sdi_document_type' => 'setSdiDocumentType',
        'attachments' => 'setAttachments',
        'uploaded_attachments' => 'setUploadedAttachments',
        'passive_invoice_rows' => 'setPassiveInvoiceRows',
        'passive_invoice_payment_conditions' => 'setPassiveInvoicePaymentConditions',
        'issuer_info' => 'setIssuerInfo',
        'recipient_info' => 'setRecipientInfo',
        'id_passive_invoice' => 'setIdPassiveInvoice',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_credit' => 'getIsCredit',
        'status' => 'getStatus',
        'id_recipient' => 'getIdRecipient',
        'recipient_code' => 'getRecipientCode',
        'recipient_vat_number' => 'getRecipientVatNumber',
        'recipient_description' => 'getRecipientDescription',
        'issuer_company' => 'getIssuerCompany',
        'issuer_vat_number' => 'getIssuerVatNumber',
        'issuer_description' => 'getIssuerDescription',
        'issuer_address' => 'getIssuerAddress',
        'issuer_zip_code' => 'getIssuerZipCode',
        'issuer_city' => 'getIssuerCity',
        'issuer_province' => 'getIssuerProvince',
        'issuer_country' => 'getIssuerCountry',
        'invoice_number' => 'getInvoiceNumber',
        'issue_date' => 'getIssueDate',
        'received_date' => 'getReceivedDate',
        'invoice_heading' => 'getInvoiceHeading',
        'net_amount' => 'getNetAmount',
        'tax' => 'getTax',
        'total' => 'getTotal',
        'net_amount_currency' => 'getNetAmountCurrency',
        'tax_currency' => 'getTaxCurrency',
        'total_currency' => 'getTotalCurrency',
        'is_to_pay' => 'getIsToPay',
        'is_paid' => 'getIsPaid',
        'payment_date' => 'getPaymentDate',
        'currency' => 'getCurrency',
        'invoice_category' => 'getInvoiceCategory',
        'alternative_invoice_category' => 'getAlternativeInvoiceCategory',
        'sdi_document_type' => 'getSdiDocumentType',
        'attachments' => 'getAttachments',
        'uploaded_attachments' => 'getUploadedAttachments',
        'passive_invoice_rows' => 'getPassiveInvoiceRows',
        'passive_invoice_payment_conditions' => 'getPassiveInvoicePaymentConditions',
        'issuer_info' => 'getIssuerInfo',
        'recipient_info' => 'getRecipientInfo',
        'id_passive_invoice' => 'getIdPassiveInvoice',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('is_credit', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('id_recipient', $data ?? [], null);
        $this->setIfExists('recipient_code', $data ?? [], null);
        $this->setIfExists('recipient_vat_number', $data ?? [], null);
        $this->setIfExists('recipient_description', $data ?? [], null);
        $this->setIfExists('issuer_company', $data ?? [], null);
        $this->setIfExists('issuer_vat_number', $data ?? [], null);
        $this->setIfExists('issuer_description', $data ?? [], null);
        $this->setIfExists('issuer_address', $data ?? [], null);
        $this->setIfExists('issuer_zip_code', $data ?? [], null);
        $this->setIfExists('issuer_city', $data ?? [], null);
        $this->setIfExists('issuer_province', $data ?? [], null);
        $this->setIfExists('issuer_country', $data ?? [], null);
        $this->setIfExists('invoice_number', $data ?? [], null);
        $this->setIfExists('issue_date', $data ?? [], null);
        $this->setIfExists('received_date', $data ?? [], null);
        $this->setIfExists('invoice_heading', $data ?? [], null);
        $this->setIfExists('net_amount', $data ?? [], null);
        $this->setIfExists('tax', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('net_amount_currency', $data ?? [], null);
        $this->setIfExists('tax_currency', $data ?? [], null);
        $this->setIfExists('total_currency', $data ?? [], null);
        $this->setIfExists('is_to_pay', $data ?? [], null);
        $this->setIfExists('is_paid', $data ?? [], null);
        $this->setIfExists('payment_date', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('invoice_category', $data ?? [], null);
        $this->setIfExists('alternative_invoice_category', $data ?? [], null);
        $this->setIfExists('sdi_document_type', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('uploaded_attachments', $data ?? [], null);
        $this->setIfExists('passive_invoice_rows', $data ?? [], null);
        $this->setIfExists('passive_invoice_payment_conditions', $data ?? [], null);
        $this->setIfExists('issuer_info', $data ?? [], null);
        $this->setIfExists('recipient_info', $data ?? [], null);
        $this->setIfExists('id_passive_invoice', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_credit
     *
     * @return bool|null
     */
    public function getIsCredit()
    {
        return $this->container['is_credit'];
    }

    /**
     * Sets is_credit
     *
     * @param bool|null $is_credit True means credit (money from issuer to recipient)
     *
     * @return self
     */
    public function setIsCredit($is_credit)
    {
        if (is_null($is_credit)) {
            throw new \InvalidArgumentException('non-nullable is_credit cannot be null');
        }
        $this->container['is_credit'] = $is_credit;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets id_recipient
     *
     * @return string|null
     */
    public function getIdRecipient()
    {
        return $this->container['id_recipient'];
    }

    /**
     * Sets id_recipient
     *
     * @param string|null $id_recipient Id Recipient
     *
     * @return self
     */
    public function setIdRecipient($id_recipient)
    {
        if (is_null($id_recipient)) {
            throw new \InvalidArgumentException('non-nullable id_recipient cannot be null');
        }
        $this->container['id_recipient'] = $id_recipient;

        return $this;
    }

    /**
     * Gets recipient_code
     *
     * @return string|null
     */
    public function getRecipientCode()
    {
        return $this->container['recipient_code'];
    }

    /**
     * Sets recipient_code
     *
     * @param string|null $recipient_code Recipient Code
     *
     * @return self
     */
    public function setRecipientCode($recipient_code)
    {
        if (is_null($recipient_code)) {
            throw new \InvalidArgumentException('non-nullable recipient_code cannot be null');
        }
        $this->container['recipient_code'] = $recipient_code;

        return $this;
    }

    /**
     * Gets recipient_vat_number
     *
     * @return string|null
     */
    public function getRecipientVatNumber()
    {
        return $this->container['recipient_vat_number'];
    }

    /**
     * Sets recipient_vat_number
     *
     * @param string|null $recipient_vat_number Recipient Vat Number
     *
     * @return self
     */
    public function setRecipientVatNumber($recipient_vat_number)
    {
        if (is_null($recipient_vat_number)) {
            throw new \InvalidArgumentException('non-nullable recipient_vat_number cannot be null');
        }
        $this->container['recipient_vat_number'] = $recipient_vat_number;

        return $this;
    }

    /**
     * Gets recipient_description
     *
     * @return string|null
     */
    public function getRecipientDescription()
    {
        return $this->container['recipient_description'];
    }

    /**
     * Sets recipient_description
     *
     * @param string|null $recipient_description Recipient Description
     *
     * @return self
     */
    public function setRecipientDescription($recipient_description)
    {
        if (is_null($recipient_description)) {
            throw new \InvalidArgumentException('non-nullable recipient_description cannot be null');
        }
        $this->container['recipient_description'] = $recipient_description;

        return $this;
    }

    /**
     * Gets issuer_company
     *
     * @return \OpenAPI\Client\Model\CompanyDto|null
     */
    public function getIssuerCompany()
    {
        return $this->container['issuer_company'];
    }

    /**
     * Sets issuer_company
     *
     * @param \OpenAPI\Client\Model\CompanyDto|null $issuer_company issuer_company
     *
     * @return self
     */
    public function setIssuerCompany($issuer_company)
    {
        if (is_null($issuer_company)) {
            throw new \InvalidArgumentException('non-nullable issuer_company cannot be null');
        }
        $this->container['issuer_company'] = $issuer_company;

        return $this;
    }

    /**
     * Gets issuer_vat_number
     *
     * @return string|null
     */
    public function getIssuerVatNumber()
    {
        return $this->container['issuer_vat_number'];
    }

    /**
     * Sets issuer_vat_number
     *
     * @param string|null $issuer_vat_number Issuer Vat Number
     *
     * @return self
     */
    public function setIssuerVatNumber($issuer_vat_number)
    {
        if (is_null($issuer_vat_number)) {
            throw new \InvalidArgumentException('non-nullable issuer_vat_number cannot be null');
        }
        $this->container['issuer_vat_number'] = $issuer_vat_number;

        return $this;
    }

    /**
     * Gets issuer_description
     *
     * @return string|null
     */
    public function getIssuerDescription()
    {
        return $this->container['issuer_description'];
    }

    /**
     * Sets issuer_description
     *
     * @param string|null $issuer_description Issuer Description
     *
     * @return self
     */
    public function setIssuerDescription($issuer_description)
    {
        if (is_null($issuer_description)) {
            throw new \InvalidArgumentException('non-nullable issuer_description cannot be null');
        }
        $this->container['issuer_description'] = $issuer_description;

        return $this;
    }

    /**
     * Gets issuer_address
     *
     * @return string|null
     */
    public function getIssuerAddress()
    {
        return $this->container['issuer_address'];
    }

    /**
     * Sets issuer_address
     *
     * @param string|null $issuer_address Issuer Address
     *
     * @return self
     */
    public function setIssuerAddress($issuer_address)
    {
        if (is_null($issuer_address)) {
            throw new \InvalidArgumentException('non-nullable issuer_address cannot be null');
        }
        $this->container['issuer_address'] = $issuer_address;

        return $this;
    }

    /**
     * Gets issuer_zip_code
     *
     * @return string|null
     */
    public function getIssuerZipCode()
    {
        return $this->container['issuer_zip_code'];
    }

    /**
     * Sets issuer_zip_code
     *
     * @param string|null $issuer_zip_code Issuer Zip Code
     *
     * @return self
     */
    public function setIssuerZipCode($issuer_zip_code)
    {
        if (is_null($issuer_zip_code)) {
            throw new \InvalidArgumentException('non-nullable issuer_zip_code cannot be null');
        }
        $this->container['issuer_zip_code'] = $issuer_zip_code;

        return $this;
    }

    /**
     * Gets issuer_city
     *
     * @return string|null
     */
    public function getIssuerCity()
    {
        return $this->container['issuer_city'];
    }

    /**
     * Sets issuer_city
     *
     * @param string|null $issuer_city Issuer City
     *
     * @return self
     */
    public function setIssuerCity($issuer_city)
    {
        if (is_null($issuer_city)) {
            throw new \InvalidArgumentException('non-nullable issuer_city cannot be null');
        }
        $this->container['issuer_city'] = $issuer_city;

        return $this;
    }

    /**
     * Gets issuer_province
     *
     * @return string|null
     */
    public function getIssuerProvince()
    {
        return $this->container['issuer_province'];
    }

    /**
     * Sets issuer_province
     *
     * @param string|null $issuer_province Issuer Province
     *
     * @return self
     */
    public function setIssuerProvince($issuer_province)
    {
        if (is_null($issuer_province)) {
            throw new \InvalidArgumentException('non-nullable issuer_province cannot be null');
        }
        $this->container['issuer_province'] = $issuer_province;

        return $this;
    }

    /**
     * Gets issuer_country
     *
     * @return \OpenAPI\Client\Model\CountryDto|null
     */
    public function getIssuerCountry()
    {
        return $this->container['issuer_country'];
    }

    /**
     * Sets issuer_country
     *
     * @param \OpenAPI\Client\Model\CountryDto|null $issuer_country issuer_country
     *
     * @return self
     */
    public function setIssuerCountry($issuer_country)
    {
        if (is_null($issuer_country)) {
            throw new \InvalidArgumentException('non-nullable issuer_country cannot be null');
        }
        $this->container['issuer_country'] = $issuer_country;

        return $this;
    }

    /**
     * Gets invoice_number
     *
     * @return string|null
     */
    public function getInvoiceNumber()
    {
        return $this->container['invoice_number'];
    }

    /**
     * Sets invoice_number
     *
     * @param string|null $invoice_number Invoice Number
     *
     * @return self
     */
    public function setInvoiceNumber($invoice_number)
    {
        if (is_null($invoice_number)) {
            throw new \InvalidArgumentException('non-nullable invoice_number cannot be null');
        }
        $this->container['invoice_number'] = $invoice_number;

        return $this;
    }

    /**
     * Gets issue_date
     *
     * @return \DateTime|null
     */
    public function getIssueDate()
    {
        return $this->container['issue_date'];
    }

    /**
     * Sets issue_date
     *
     * @param \DateTime|null $issue_date Issue Date
     *
     * @return self
     */
    public function setIssueDate($issue_date)
    {
        if (is_null($issue_date)) {
            throw new \InvalidArgumentException('non-nullable issue_date cannot be null');
        }
        $this->container['issue_date'] = $issue_date;

        return $this;
    }

    /**
     * Gets received_date
     *
     * @return \DateTime|null
     */
    public function getReceivedDate()
    {
        return $this->container['received_date'];
    }

    /**
     * Sets received_date
     *
     * @param \DateTime|null $received_date Received Date
     *
     * @return self
     */
    public function setReceivedDate($received_date)
    {
        if (is_null($received_date)) {
            throw new \InvalidArgumentException('non-nullable received_date cannot be null');
        }
        $this->container['received_date'] = $received_date;

        return $this;
    }

    /**
     * Gets invoice_heading
     *
     * @return string|null
     */
    public function getInvoiceHeading()
    {
        return $this->container['invoice_heading'];
    }

    /**
     * Sets invoice_heading
     *
     * @param string|null $invoice_heading Invoice Heading
     *
     * @return self
     */
    public function setInvoiceHeading($invoice_heading)
    {
        if (is_null($invoice_heading)) {
            throw new \InvalidArgumentException('non-nullable invoice_heading cannot be null');
        }
        $this->container['invoice_heading'] = $invoice_heading;

        return $this;
    }

    /**
     * Gets net_amount
     *
     * @return float|null
     */
    public function getNetAmount()
    {
        return $this->container['net_amount'];
    }

    /**
     * Sets net_amount
     *
     * @param float|null $net_amount Net Amount
     *
     * @return self
     */
    public function setNetAmount($net_amount)
    {
        if (is_null($net_amount)) {
            throw new \InvalidArgumentException('non-nullable net_amount cannot be null');
        }
        $this->container['net_amount'] = $net_amount;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return float|null
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param float|null $tax Tax
     *
     * @return self
     */
    public function setTax($tax)
    {
        if (is_null($tax)) {
            throw new \InvalidArgumentException('non-nullable tax cannot be null');
        }
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets total
     *
     * @return float|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param float|null $total Total
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets net_amount_currency
     *
     * @return float|null
     */
    public function getNetAmountCurrency()
    {
        return $this->container['net_amount_currency'];
    }

    /**
     * Sets net_amount_currency
     *
     * @param float|null $net_amount_currency Net Amount, in the Currency, if set
     *
     * @return self
     */
    public function setNetAmountCurrency($net_amount_currency)
    {
        if (is_null($net_amount_currency)) {
            throw new \InvalidArgumentException('non-nullable net_amount_currency cannot be null');
        }
        $this->container['net_amount_currency'] = $net_amount_currency;

        return $this;
    }

    /**
     * Gets tax_currency
     *
     * @return float|null
     */
    public function getTaxCurrency()
    {
        return $this->container['tax_currency'];
    }

    /**
     * Sets tax_currency
     *
     * @param float|null $tax_currency Tax, in the Currency, if set
     *
     * @return self
     */
    public function setTaxCurrency($tax_currency)
    {
        if (is_null($tax_currency)) {
            throw new \InvalidArgumentException('non-nullable tax_currency cannot be null');
        }
        $this->container['tax_currency'] = $tax_currency;

        return $this;
    }

    /**
     * Gets total_currency
     *
     * @return float|null
     */
    public function getTotalCurrency()
    {
        return $this->container['total_currency'];
    }

    /**
     * Sets total_currency
     *
     * @param float|null $total_currency Total, in the Currency, if set
     *
     * @return self
     */
    public function setTotalCurrency($total_currency)
    {
        if (is_null($total_currency)) {
            throw new \InvalidArgumentException('non-nullable total_currency cannot be null');
        }
        $this->container['total_currency'] = $total_currency;

        return $this;
    }

    /**
     * Gets is_to_pay
     *
     * @return bool|null
     */
    public function getIsToPay()
    {
        return $this->container['is_to_pay'];
    }

    /**
     * Sets is_to_pay
     *
     * @param bool|null $is_to_pay True if the invoice is to pay
     *
     * @return self
     */
    public function setIsToPay($is_to_pay)
    {
        if (is_null($is_to_pay)) {
            throw new \InvalidArgumentException('non-nullable is_to_pay cannot be null');
        }
        $this->container['is_to_pay'] = $is_to_pay;

        return $this;
    }

    /**
     * Gets is_paid
     *
     * @return bool|null
     */
    public function getIsPaid()
    {
        return $this->container['is_paid'];
    }

    /**
     * Sets is_paid
     *
     * @param bool|null $is_paid True if the invoice is paid
     *
     * @return self
     */
    public function setIsPaid($is_paid)
    {
        if (is_null($is_paid)) {
            throw new \InvalidArgumentException('non-nullable is_paid cannot be null');
        }
        $this->container['is_paid'] = $is_paid;

        return $this;
    }

    /**
     * Gets payment_date
     *
     * @return \DateTime|null
     */
    public function getPaymentDate()
    {
        return $this->container['payment_date'];
    }

    /**
     * Sets payment_date
     *
     * @param \DateTime|null $payment_date The date of payment, if managed
     *
     * @return self
     */
    public function setPaymentDate($payment_date)
    {
        if (is_null($payment_date)) {
            throw new \InvalidArgumentException('non-nullable payment_date cannot be null');
        }
        $this->container['payment_date'] = $payment_date;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \OpenAPI\Client\Model\CurrencyDto|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \OpenAPI\Client\Model\CurrencyDto|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets invoice_category
     *
     * @return \OpenAPI\Client\Model\InvoiceCategoryDto|null
     */
    public function getInvoiceCategory()
    {
        return $this->container['invoice_category'];
    }

    /**
     * Sets invoice_category
     *
     * @param \OpenAPI\Client\Model\InvoiceCategoryDto|null $invoice_category invoice_category
     *
     * @return self
     */
    public function setInvoiceCategory($invoice_category)
    {
        if (is_null($invoice_category)) {
            throw new \InvalidArgumentException('non-nullable invoice_category cannot be null');
        }
        $this->container['invoice_category'] = $invoice_category;

        return $this;
    }

    /**
     * Gets alternative_invoice_category
     *
     * @return \OpenAPI\Client\Model\InvoiceCategoryDto|null
     */
    public function getAlternativeInvoiceCategory()
    {
        return $this->container['alternative_invoice_category'];
    }

    /**
     * Sets alternative_invoice_category
     *
     * @param \OpenAPI\Client\Model\InvoiceCategoryDto|null $alternative_invoice_category alternative_invoice_category
     *
     * @return self
     */
    public function setAlternativeInvoiceCategory($alternative_invoice_category)
    {
        if (is_null($alternative_invoice_category)) {
            throw new \InvalidArgumentException('non-nullable alternative_invoice_category cannot be null');
        }
        $this->container['alternative_invoice_category'] = $alternative_invoice_category;

        return $this;
    }

    /**
     * Gets sdi_document_type
     *
     * @return string|null
     */
    public function getSdiDocumentType()
    {
        return $this->container['sdi_document_type'];
    }

    /**
     * Sets sdi_document_type
     *
     * @param string|null $sdi_document_type The Invoice SDI Document type
     *
     * @return self
     */
    public function setSdiDocumentType($sdi_document_type)
    {
        if (is_null($sdi_document_type)) {
            throw new \InvalidArgumentException('non-nullable sdi_document_type cannot be null');
        }
        $this->container['sdi_document_type'] = $sdi_document_type;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \OpenAPI\Client\Model\PassiveInvoiceAttachmentDto[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \OpenAPI\Client\Model\PassiveInvoiceAttachmentDto[]|null $attachments Attachments files
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets uploaded_attachments
     *
     * @return \OpenAPI\Client\Model\FileInfoDto[]|null
     */
    public function getUploadedAttachments()
    {
        return $this->container['uploaded_attachments'];
    }

    /**
     * Sets uploaded_attachments
     *
     * @param \OpenAPI\Client\Model\FileInfoDto[]|null $uploaded_attachments Gets or sets the uploaded attachments.
     *
     * @return self
     */
    public function setUploadedAttachments($uploaded_attachments)
    {
        if (is_null($uploaded_attachments)) {
            throw new \InvalidArgumentException('non-nullable uploaded_attachments cannot be null');
        }
        $this->container['uploaded_attachments'] = $uploaded_attachments;

        return $this;
    }

    /**
     * Gets passive_invoice_rows
     *
     * @return \OpenAPI\Client\Model\PassiveInvoiceRowDto[]|null
     */
    public function getPassiveInvoiceRows()
    {
        return $this->container['passive_invoice_rows'];
    }

    /**
     * Sets passive_invoice_rows
     *
     * @param \OpenAPI\Client\Model\PassiveInvoiceRowDto[]|null $passive_invoice_rows Rows
     *
     * @return self
     */
    public function setPassiveInvoiceRows($passive_invoice_rows)
    {
        if (is_null($passive_invoice_rows)) {
            throw new \InvalidArgumentException('non-nullable passive_invoice_rows cannot be null');
        }
        $this->container['passive_invoice_rows'] = $passive_invoice_rows;

        return $this;
    }

    /**
     * Gets passive_invoice_payment_conditions
     *
     * @return \OpenAPI\Client\Model\PassiveInvoicePaymentConditionDto[]|null
     */
    public function getPassiveInvoicePaymentConditions()
    {
        return $this->container['passive_invoice_payment_conditions'];
    }

    /**
     * Sets passive_invoice_payment_conditions
     *
     * @param \OpenAPI\Client\Model\PassiveInvoicePaymentConditionDto[]|null $passive_invoice_payment_conditions Rows
     *
     * @return self
     */
    public function setPassiveInvoicePaymentConditions($passive_invoice_payment_conditions)
    {
        if (is_null($passive_invoice_payment_conditions)) {
            throw new \InvalidArgumentException('non-nullable passive_invoice_payment_conditions cannot be null');
        }
        $this->container['passive_invoice_payment_conditions'] = $passive_invoice_payment_conditions;

        return $this;
    }

    /**
     * Gets issuer_info
     *
     * @return string|null
     */
    public function getIssuerInfo()
    {
        return $this->container['issuer_info'];
    }

    /**
     * Sets issuer_info
     *
     * @param string|null $issuer_info Issuer Info
     *
     * @return self
     */
    public function setIssuerInfo($issuer_info)
    {
        if (is_null($issuer_info)) {
            throw new \InvalidArgumentException('non-nullable issuer_info cannot be null');
        }
        $this->container['issuer_info'] = $issuer_info;

        return $this;
    }

    /**
     * Gets recipient_info
     *
     * @return string|null
     */
    public function getRecipientInfo()
    {
        return $this->container['recipient_info'];
    }

    /**
     * Sets recipient_info
     *
     * @param string|null $recipient_info Recipient Info
     *
     * @return self
     */
    public function setRecipientInfo($recipient_info)
    {
        if (is_null($recipient_info)) {
            throw new \InvalidArgumentException('non-nullable recipient_info cannot be null');
        }
        $this->container['recipient_info'] = $recipient_info;

        return $this;
    }

    /**
     * Gets id_passive_invoice
     *
     * @return int|null
     */
    public function getIdPassiveInvoice()
    {
        return $this->container['id_passive_invoice'];
    }

    /**
     * Sets id_passive_invoice
     *
     * @param int|null $id_passive_invoice Reference to the original sdi.PassiveInvoice, if the invoice comes from SDI.
     *
     * @return self
     */
    public function setIdPassiveInvoice($id_passive_invoice)
    {
        if (is_null($id_passive_invoice)) {
            throw new \InvalidArgumentException('non-nullable id_passive_invoice cannot be null');
        }
        $this->container['id_passive_invoice'] = $id_passive_invoice;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Gets or sets the identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


