<?php
/**
 * TabularFieldDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TabularFieldDto Class Doc Comment
 *
 * @category Class
 * @description Tabular Field
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TabularFieldDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TabularFieldDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'object_id' => 'int',
        'name' => 'string',
        'original_display_name' => 'string',
        'display_name' => 'string',
        'complete_field_name' => 'string',
        'data_type' => 'string',
        'format_string' => 'string',
        'next_value' => 'object',
        'filters' => '\OpenAPI\Client\Model\TabularFieldFilterDto[]',
        'is_export_hidden' => 'bool',
        'extraction_order' => 'int',
        'fields_type' => 'string',
        'description' => 'string',
        'order' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'object_id' => 'int32',
        'name' => null,
        'original_display_name' => null,
        'display_name' => null,
        'complete_field_name' => null,
        'data_type' => null,
        'format_string' => null,
        'next_value' => null,
        'filters' => null,
        'is_export_hidden' => null,
        'extraction_order' => 'int32',
        'fields_type' => null,
        'description' => null,
        'order' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'object_id' => false,
        'name' => false,
        'original_display_name' => false,
        'display_name' => false,
        'complete_field_name' => false,
        'data_type' => false,
        'format_string' => false,
        'next_value' => false,
        'filters' => false,
        'is_export_hidden' => false,
        'extraction_order' => false,
        'fields_type' => false,
        'description' => false,
        'order' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'object_id' => 'ObjectId',
        'name' => 'Name',
        'original_display_name' => 'OriginalDisplayName',
        'display_name' => 'DisplayName',
        'complete_field_name' => 'CompleteFieldName',
        'data_type' => 'DataType',
        'format_string' => 'FormatString',
        'next_value' => 'NextValue',
        'filters' => 'Filters',
        'is_export_hidden' => 'IsExportHidden',
        'extraction_order' => 'ExtractionOrder',
        'fields_type' => 'FieldsType',
        'description' => 'Description',
        'order' => 'Order'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'object_id' => 'setObjectId',
        'name' => 'setName',
        'original_display_name' => 'setOriginalDisplayName',
        'display_name' => 'setDisplayName',
        'complete_field_name' => 'setCompleteFieldName',
        'data_type' => 'setDataType',
        'format_string' => 'setFormatString',
        'next_value' => 'setNextValue',
        'filters' => 'setFilters',
        'is_export_hidden' => 'setIsExportHidden',
        'extraction_order' => 'setExtractionOrder',
        'fields_type' => 'setFieldsType',
        'description' => 'setDescription',
        'order' => 'setOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'object_id' => 'getObjectId',
        'name' => 'getName',
        'original_display_name' => 'getOriginalDisplayName',
        'display_name' => 'getDisplayName',
        'complete_field_name' => 'getCompleteFieldName',
        'data_type' => 'getDataType',
        'format_string' => 'getFormatString',
        'next_value' => 'getNextValue',
        'filters' => 'getFilters',
        'is_export_hidden' => 'getIsExportHidden',
        'extraction_order' => 'getExtractionOrder',
        'fields_type' => 'getFieldsType',
        'description' => 'getDescription',
        'order' => 'getOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DATA_TYPE_UNDEFINED = 'Undefined';
    public const DATA_TYPE_AUTOMATIC = 'Automatic';
    public const DATA_TYPE_STRING = 'String';
    public const DATA_TYPE_INT64 = 'Int64';
    public const DATA_TYPE_DOUBLE = 'Double';
    public const DATA_TYPE_DATE_TIME = 'DateTime';
    public const DATA_TYPE_DECIMAL = 'Decimal';
    public const DATA_TYPE_BOOLEAN = 'Boolean';
    public const DATA_TYPE_BINARY = 'Binary';
    public const DATA_TYPE_UNKNOWN = 'Unknown';
    public const DATA_TYPE_VARIANT = 'Variant';
    public const FIELDS_TYPE_NONE = 'None';
    public const FIELDS_TYPE_STANDARD_COLUMN = 'StandardColumn';
    public const FIELDS_TYPE_COMPUTED_COLUMN = 'ComputedColumn';
    public const FIELDS_TYPE_MEASURE = 'Measure';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDataTypeAllowableValues()
    {
        return [
            self::DATA_TYPE_UNDEFINED,
            self::DATA_TYPE_AUTOMATIC,
            self::DATA_TYPE_STRING,
            self::DATA_TYPE_INT64,
            self::DATA_TYPE_DOUBLE,
            self::DATA_TYPE_DATE_TIME,
            self::DATA_TYPE_DECIMAL,
            self::DATA_TYPE_BOOLEAN,
            self::DATA_TYPE_BINARY,
            self::DATA_TYPE_UNKNOWN,
            self::DATA_TYPE_VARIANT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFieldsTypeAllowableValues()
    {
        return [
            self::FIELDS_TYPE_NONE,
            self::FIELDS_TYPE_STANDARD_COLUMN,
            self::FIELDS_TYPE_COMPUTED_COLUMN,
            self::FIELDS_TYPE_MEASURE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('object_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('original_display_name', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('complete_field_name', $data ?? [], null);
        $this->setIfExists('data_type', $data ?? [], null);
        $this->setIfExists('format_string', $data ?? [], null);
        $this->setIfExists('next_value', $data ?? [], null);
        $this->setIfExists('filters', $data ?? [], null);
        $this->setIfExists('is_export_hidden', $data ?? [], null);
        $this->setIfExists('extraction_order', $data ?? [], null);
        $this->setIfExists('fields_type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('order', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDataTypeAllowableValues();
        if (!is_null($this->container['data_type']) && !in_array($this->container['data_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'data_type', must be one of '%s'",
                $this->container['data_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFieldsTypeAllowableValues();
        if (!is_null($this->container['fields_type']) && !in_array($this->container['fields_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fields_type', must be one of '%s'",
                $this->container['fields_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets object_id
     *
     * @return int|null
     */
    public function getObjectId()
    {
        return $this->container['object_id'];
    }

    /**
     * Sets object_id
     *
     * @param int|null $object_id object_id
     *
     * @return self
     */
    public function setObjectId($object_id)
    {
        if (is_null($object_id)) {
            throw new \InvalidArgumentException('non-nullable object_id cannot be null');
        }
        $this->container['object_id'] = $object_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets original_display_name
     *
     * @return string|null
     */
    public function getOriginalDisplayName()
    {
        return $this->container['original_display_name'];
    }

    /**
     * Sets original_display_name
     *
     * @param string|null $original_display_name original_display_name
     *
     * @return self
     */
    public function setOriginalDisplayName($original_display_name)
    {
        if (is_null($original_display_name)) {
            throw new \InvalidArgumentException('non-nullable original_display_name cannot be null');
        }
        $this->container['original_display_name'] = $original_display_name;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets complete_field_name
     *
     * @return string|null
     */
    public function getCompleteFieldName()
    {
        return $this->container['complete_field_name'];
    }

    /**
     * Sets complete_field_name
     *
     * @param string|null $complete_field_name complete_field_name
     *
     * @return self
     */
    public function setCompleteFieldName($complete_field_name)
    {
        if (is_null($complete_field_name)) {
            throw new \InvalidArgumentException('non-nullable complete_field_name cannot be null');
        }
        $this->container['complete_field_name'] = $complete_field_name;

        return $this;
    }

    /**
     * Gets data_type
     *
     * @return string|null
     */
    public function getDataType()
    {
        return $this->container['data_type'];
    }

    /**
     * Sets data_type
     *
     * @param string|null $data_type data_type
     *
     * @return self
     */
    public function setDataType($data_type)
    {
        if (is_null($data_type)) {
            throw new \InvalidArgumentException('non-nullable data_type cannot be null');
        }
        $allowedValues = $this->getDataTypeAllowableValues();
        if (!in_array($data_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'data_type', must be one of '%s'",
                    $data_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['data_type'] = $data_type;

        return $this;
    }

    /**
     * Gets format_string
     *
     * @return string|null
     */
    public function getFormatString()
    {
        return $this->container['format_string'];
    }

    /**
     * Sets format_string
     *
     * @param string|null $format_string format_string
     *
     * @return self
     */
    public function setFormatString($format_string)
    {
        if (is_null($format_string)) {
            throw new \InvalidArgumentException('non-nullable format_string cannot be null');
        }
        $this->container['format_string'] = $format_string;

        return $this;
    }

    /**
     * Gets next_value
     *
     * @return object|null
     */
    public function getNextValue()
    {
        return $this->container['next_value'];
    }

    /**
     * Sets next_value
     *
     * @param object|null $next_value next_value
     *
     * @return self
     */
    public function setNextValue($next_value)
    {
        if (is_null($next_value)) {
            throw new \InvalidArgumentException('non-nullable next_value cannot be null');
        }
        $this->container['next_value'] = $next_value;

        return $this;
    }

    /**
     * Gets filters
     *
     * @return \OpenAPI\Client\Model\TabularFieldFilterDto[]|null
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     *
     * @param \OpenAPI\Client\Model\TabularFieldFilterDto[]|null $filters filters
     *
     * @return self
     */
    public function setFilters($filters)
    {
        if (is_null($filters)) {
            throw new \InvalidArgumentException('non-nullable filters cannot be null');
        }
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets is_export_hidden
     *
     * @return bool|null
     */
    public function getIsExportHidden()
    {
        return $this->container['is_export_hidden'];
    }

    /**
     * Sets is_export_hidden
     *
     * @param bool|null $is_export_hidden is_export_hidden
     *
     * @return self
     */
    public function setIsExportHidden($is_export_hidden)
    {
        if (is_null($is_export_hidden)) {
            throw new \InvalidArgumentException('non-nullable is_export_hidden cannot be null');
        }
        $this->container['is_export_hidden'] = $is_export_hidden;

        return $this;
    }

    /**
     * Gets extraction_order
     *
     * @return int|null
     */
    public function getExtractionOrder()
    {
        return $this->container['extraction_order'];
    }

    /**
     * Sets extraction_order
     *
     * @param int|null $extraction_order extraction_order
     *
     * @return self
     */
    public function setExtractionOrder($extraction_order)
    {
        if (is_null($extraction_order)) {
            throw new \InvalidArgumentException('non-nullable extraction_order cannot be null');
        }
        $this->container['extraction_order'] = $extraction_order;

        return $this;
    }

    /**
     * Gets fields_type
     *
     * @return string|null
     */
    public function getFieldsType()
    {
        return $this->container['fields_type'];
    }

    /**
     * Sets fields_type
     *
     * @param string|null $fields_type fields_type
     *
     * @return self
     */
    public function setFieldsType($fields_type)
    {
        if (is_null($fields_type)) {
            throw new \InvalidArgumentException('non-nullable fields_type cannot be null');
        }
        $allowedValues = $this->getFieldsTypeAllowableValues();
        if (!in_array($fields_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fields_type', must be one of '%s'",
                    $fields_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fields_type'] = $fields_type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets order
     *
     * @return int|null
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param int|null $order order
     *
     * @return self
     */
    public function setOrder($order)
    {
        if (is_null($order)) {
            throw new \InvalidArgumentException('non-nullable order cannot be null');
        }
        $this->container['order'] = $order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


