<?php
/**
 * UpdateDealerCountersBlendedToStandardRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UpdateDealerCountersBlendedToStandardRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateDealerCountersBlendedToStandardRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateDealerCountersBlendedToStandardRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'use_counter_standard' => 'bool',
        'dealer_code' => 'string',
        'brand' => 'string',
        'id_product' => 'string',
        'is_hp_wpp' => 'bool',
        'mono_id' => 'string',
        'color_id' => 'string',
        'mono_a3_id' => 'string',
        'color_a3_id' => 'string',
        'fax_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'use_counter_standard' => null,
        'dealer_code' => null,
        'brand' => null,
        'id_product' => null,
        'is_hp_wpp' => null,
        'mono_id' => null,
        'color_id' => null,
        'mono_a3_id' => null,
        'color_a3_id' => null,
        'fax_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'use_counter_standard' => false,
        'dealer_code' => false,
        'brand' => false,
        'id_product' => false,
        'is_hp_wpp' => false,
        'mono_id' => false,
        'color_id' => false,
        'mono_a3_id' => false,
        'color_a3_id' => false,
        'fax_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'use_counter_standard' => 'UseCounterStandard',
        'dealer_code' => 'DealerCode',
        'brand' => 'Brand',
        'id_product' => 'IdProduct',
        'is_hp_wpp' => 'IsHpWpp',
        'mono_id' => 'MonoId',
        'color_id' => 'ColorId',
        'mono_a3_id' => 'MonoA3Id',
        'color_a3_id' => 'ColorA3Id',
        'fax_id' => 'FaxId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'use_counter_standard' => 'setUseCounterStandard',
        'dealer_code' => 'setDealerCode',
        'brand' => 'setBrand',
        'id_product' => 'setIdProduct',
        'is_hp_wpp' => 'setIsHpWpp',
        'mono_id' => 'setMonoId',
        'color_id' => 'setColorId',
        'mono_a3_id' => 'setMonoA3Id',
        'color_a3_id' => 'setColorA3Id',
        'fax_id' => 'setFaxId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'use_counter_standard' => 'getUseCounterStandard',
        'dealer_code' => 'getDealerCode',
        'brand' => 'getBrand',
        'id_product' => 'getIdProduct',
        'is_hp_wpp' => 'getIsHpWpp',
        'mono_id' => 'getMonoId',
        'color_id' => 'getColorId',
        'mono_a3_id' => 'getMonoA3Id',
        'color_a3_id' => 'getColorA3Id',
        'fax_id' => 'getFaxId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('use_counter_standard', $data ?? [], null);
        $this->setIfExists('dealer_code', $data ?? [], null);
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('id_product', $data ?? [], null);
        $this->setIfExists('is_hp_wpp', $data ?? [], null);
        $this->setIfExists('mono_id', $data ?? [], null);
        $this->setIfExists('color_id', $data ?? [], null);
        $this->setIfExists('mono_a3_id', $data ?? [], null);
        $this->setIfExists('color_a3_id', $data ?? [], null);
        $this->setIfExists('fax_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets use_counter_standard
     *
     * @return bool|null
     */
    public function getUseCounterStandard()
    {
        return $this->container['use_counter_standard'];
    }

    /**
     * Sets use_counter_standard
     *
     * @param bool|null $use_counter_standard use_counter_standard
     *
     * @return self
     */
    public function setUseCounterStandard($use_counter_standard)
    {
        if (is_null($use_counter_standard)) {
            throw new \InvalidArgumentException('non-nullable use_counter_standard cannot be null');
        }
        $this->container['use_counter_standard'] = $use_counter_standard;

        return $this;
    }

    /**
     * Gets dealer_code
     *
     * @return string|null
     */
    public function getDealerCode()
    {
        return $this->container['dealer_code'];
    }

    /**
     * Sets dealer_code
     *
     * @param string|null $dealer_code dealer_code
     *
     * @return self
     */
    public function setDealerCode($dealer_code)
    {
        if (is_null($dealer_code)) {
            throw new \InvalidArgumentException('non-nullable dealer_code cannot be null');
        }
        $this->container['dealer_code'] = $dealer_code;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string|null $brand brand
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets id_product
     *
     * @return string|null
     */
    public function getIdProduct()
    {
        return $this->container['id_product'];
    }

    /**
     * Sets id_product
     *
     * @param string|null $id_product id_product
     *
     * @return self
     */
    public function setIdProduct($id_product)
    {
        if (is_null($id_product)) {
            throw new \InvalidArgumentException('non-nullable id_product cannot be null');
        }
        $this->container['id_product'] = $id_product;

        return $this;
    }

    /**
     * Gets is_hp_wpp
     *
     * @return bool|null
     */
    public function getIsHpWpp()
    {
        return $this->container['is_hp_wpp'];
    }

    /**
     * Sets is_hp_wpp
     *
     * @param bool|null $is_hp_wpp is_hp_wpp
     *
     * @return self
     */
    public function setIsHpWpp($is_hp_wpp)
    {
        if (is_null($is_hp_wpp)) {
            throw new \InvalidArgumentException('non-nullable is_hp_wpp cannot be null');
        }
        $this->container['is_hp_wpp'] = $is_hp_wpp;

        return $this;
    }

    /**
     * Gets mono_id
     *
     * @return string|null
     */
    public function getMonoId()
    {
        return $this->container['mono_id'];
    }

    /**
     * Sets mono_id
     *
     * @param string|null $mono_id mono_id
     *
     * @return self
     */
    public function setMonoId($mono_id)
    {
        if (is_null($mono_id)) {
            throw new \InvalidArgumentException('non-nullable mono_id cannot be null');
        }
        $this->container['mono_id'] = $mono_id;

        return $this;
    }

    /**
     * Gets color_id
     *
     * @return string|null
     */
    public function getColorId()
    {
        return $this->container['color_id'];
    }

    /**
     * Sets color_id
     *
     * @param string|null $color_id color_id
     *
     * @return self
     */
    public function setColorId($color_id)
    {
        if (is_null($color_id)) {
            throw new \InvalidArgumentException('non-nullable color_id cannot be null');
        }
        $this->container['color_id'] = $color_id;

        return $this;
    }

    /**
     * Gets mono_a3_id
     *
     * @return string|null
     */
    public function getMonoA3Id()
    {
        return $this->container['mono_a3_id'];
    }

    /**
     * Sets mono_a3_id
     *
     * @param string|null $mono_a3_id mono_a3_id
     *
     * @return self
     */
    public function setMonoA3Id($mono_a3_id)
    {
        if (is_null($mono_a3_id)) {
            throw new \InvalidArgumentException('non-nullable mono_a3_id cannot be null');
        }
        $this->container['mono_a3_id'] = $mono_a3_id;

        return $this;
    }

    /**
     * Gets color_a3_id
     *
     * @return string|null
     */
    public function getColorA3Id()
    {
        return $this->container['color_a3_id'];
    }

    /**
     * Sets color_a3_id
     *
     * @param string|null $color_a3_id color_a3_id
     *
     * @return self
     */
    public function setColorA3Id($color_a3_id)
    {
        if (is_null($color_a3_id)) {
            throw new \InvalidArgumentException('non-nullable color_a3_id cannot be null');
        }
        $this->container['color_a3_id'] = $color_a3_id;

        return $this;
    }

    /**
     * Gets fax_id
     *
     * @return string|null
     */
    public function getFaxId()
    {
        return $this->container['fax_id'];
    }

    /**
     * Sets fax_id
     *
     * @param string|null $fax_id fax_id
     *
     * @return self
     */
    public function setFaxId($fax_id)
    {
        if (is_null($fax_id)) {
            throw new \InvalidArgumentException('non-nullable fax_id cannot be null');
        }
        $this->container['fax_id'] = $fax_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


