using System;
using System.Collections.Generic;
using System.Text;

namespace MpsMonitor.Sdk.Models.Enums
{
    public enum JamOperationResultEnum
    {
        AbortedByMps = -1,
        Unknown = 0,
        Pending = 1,
        InProgress = 2,
        SubmittedToConnectorQueue = 3,
        Success = 4,
        Applied = 5,
        UserCanceled = 6,
        FinishedWithErrors = 7,
        TimedOut = 8,
        SnmpV1V2ReadCredentialsNeeded = 9,
        SnmpV1V2WriteCredentialsNeeded = 10,
        SnmpV1V2ReadOnlyMode = 11,
        SnmpV3CredentialsNeeded = 12,
        HttpCredentialsNeeded = 13,
        DeviceCommunicationError = 14,
        DeviceIdentityUnverifiedCredentialError = 15,
        NonHPCartridgeInstalled = 16,
        UsedCartridgeInstalled = 17,
        CartridgeInBadState = 18,
        NonHPCartridgeUsageExceedsLimit = 19,
        DeviceIdentityMismatch = 20,
        ConnectorNameResolutionError = 21,
        ConnectorNameResolutionFailure = 22,
        SetVerificationError = 23,
        DeviceError = 24,
        InvalidDeviceData = 25,
        DeviceDateTimeNotInSync = 26,
        DeviceNotFound = 27,
        PartialSupport = 28,
        PolicyNotSupported = 29,
        DeviceNotSupported = 30,
        UnsupportedNetworkModel = 31,
        ConnectorUnavailable = 32,
        ConnectorNotEnabled = 33,
        InternalError = 34,
        DeviceDeleted = 35,
        ValueNotSupported = 36,
        NonHPAuthorizedDealer = 37,
        FirmwareUpgradeInProgress = 38,
        RebootModeDeviceMonitorFailure = 39,
        MissingLicense = 40,
        ItemNotFound = 41,
        NotSupportedByModel = 42,
        DeviceLicenseNotSupportedByFirmware = 43,
        DownloadFirmwareFailure = 44,
        NotSupported = 45,
        OperationDelayed = 46,
        Snapped = 47,
        FinishedWithFirmwareMismatch = 48,
        DeviceIdentificationFailed = 49,
        ItemNotSupported = 50,
        LicenseExpired = 51,
        LicenseSetFailed = 52,
        UpgradeFirmwareDeviceMonitorFailure = 53,
        ConnectorUpgradeInProgress = 54,
        HostSnmpV3FipsComplianceFailure = 55,
        SendingFirmwareToDeviceFailed = 56,
        Compliant = 57,
        NonCompliant = 58
    }
}
