openapi: 3.1.0
info:
  title: GitHub Full Access API
  description: Custom action to access GitHub with full permissions using OAuth.
  version: 1.0.0

servers:
  - url: https://api.github.com
    description: GitHub API

paths:
  /user:
    get:
      operationId: getAuthenticatedUser
      summary: Get authenticated GitHub user
      description: Retrieves the currently authenticated user's profile.
      security:
        - githubOAuth: [repo, user, gist, read:org, write:org, admin:org_hook, notifications, workflow]
      responses:
        '200':
          description: Authenticated user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  login:
                    type: string
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  avatar_url:
                    type: string
        '401':
          description: Unauthorized

  /user/repos:
    get:
      operationId: listUserRepos
      summary: List all repositories of authenticated user
      description: Lists all repositories that the authenticated user has explicit permission to access.
      security:
        - githubOAuth: [repo]
      parameters:
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Array of repository objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    full_name:
                      type: string
                    html_url:
                      type: string
                    private:
                      type: boolean
                    description:
                      type: string
        '401':
          description: Unauthorized

components:
  securitySchemes:
    githubOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/authorize
          tokenUrl: https://github.com/login/oauth/access_token
          scopes:
            repo: Full control of private repositories
            user: Read/write access to user profile (including email)
            gist: Create and manage gists
            read:org: Read organization membership
            write:org: Modify organization membership
            admin:org_hook: Manage organization webhooks
            notifications: Read and manage notifications
            workflow: Update and rerun GitHub Actions workflows
  schemas: {}
