<?php declare(strict_types=1);
// /views/dashboard.php
error_reporting(E_ALL);ini_set('display_errors','1');ini_set('log_errors','1');ini_set('error_log',__DIR__.'/../logs/debug.log');
require_once __DIR__.'/../includes/api_functions.php';$config=parse_env_file(__DIR__.'/../.env');
$customerCode=$_GET['customer']??$_COOKIE['customer']??$config['DEALER_CODE']??'';if(isset($_GET['customer']))setcookie('customer',$customerCode,time()+31536000,'/');
$customerName='All Customers';try{$resp=call_api($config,'POST','Customer/GetCustomers',['DealerCode'=>$config['DEALER_CODE']??'','PageNumber'=>1,'PageRows'=>2147483647,'SortColumn'=>'Description','SortOrder'=>'Asc']);foreach($resp['customers']??$resp['Result']??[]as$c){if(($c['Code']??'')===$customerCode){$customerName=$c['Description']??$c['Name']??'All Customers';break;}}}catch(Throwable$e){}
$cardsConfig=include __DIR__.'/../config/cards.php';$allIds=array_keys($cardsConfig);
if(isset($_COOKIE['visible_cards'])){$sel=array_filter(array_map('trim',explode(',',$_COOKIE['visible_cards'])),'strlen');$visibleIds=count($sel)>0?array_values(array_intersect($sel,$allIds)):$allIds;}else{$visibleIds=$allIds;}
?><!DOCTYPE html><html lang="en" class="h-full dark"><head><meta charset="UTF-8"/><title>Dashboard – <?=htmlspecialchars($customerName)?></title><link rel="stylesheet" href="/public/css/styles.css"/></head><body class="flex flex-col h-full bg-gray-900 text-gray-100"><?php include __DIR__.'/../components/preferences-modal.php'; ?><header class="dashboard-header flex items-center justify-between px-6 py-3 bg-gray-800 bg-opacity-50 backdrop-blur-sm"><h1 class="text-xl font-semibold"><?=htmlspecialchars($customerName)?></h1><button id="preferences-toggle" onclick="togglePreferencesModal(true)" class="p-3 rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-purple-400" title="Preferences"><i data-feather="settings" class="h-8 w-8 text-purple-400"></i></button></header><main class="flex-1 overflow-auto p-6"><div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"><?php foreach($visibleIds as$id){$file=__DIR__.'/../cards/card_'.$id.'.php';if(file_exists($file)){include $file;}else{echo "<div class='panel text-red-500'>Missing card: $id</div>";}}?></div></main></body></html>
