using System;
using System.Collections.Generic;
using System.Text;

namespace MpsMonitor.Sdk.Models.Enums
{
    public enum JamConfigItemEnum
    {
        AdminPassword = 1,
        AllowUserCreateAccount = 2,
        AppletalkEnabled = 3,
        AssetNumber = 4,
        CartridgeLife = 5,
        CompanyContact = 6,
        CompanyName = 7,
        CorsEnabled = 8,
        CorsTrustedSites = 9,
        CountDetails = 10,
        CountTotals = 11,
        Coverage = 12,
        DefaultMediaSize = 13,
        DefaultPrintCopy = 14,
        DeviceAnnouncementConfigServer = 15,
        DeviceAnnouncementEnable = 16,
        DeviceAnnouncementRequireMutualAuth = 17,
        DeviceDateTime = 18,
        DeviceLocation = 19,
        DeviceName = 20,
        EPrintSetting = 21,
        EwsPageLanguage = 22,
        FileSystemAccessNfsEnabled = 23,
        FileSystemAccessPjlEnabled = 24,
        FileSystemAccessPmlEnabled = 25,
        FileSystemAccessPsEnabled = 26,
        FileSystemPassword = 27,
        FileSystemSettings = 28,
        FtpEnabled = 29,
        FtpFirmwareUpdate = 30,
        HttpIdleTimeout = 31,
        HttpsRedirectEnabled = 32,
        InactivityTimeout = 33,
        JamRecovery = 34,
        LongLifeConsumablesLife = 35,
        LostMessageNotification = 36,
        ManualFeedPrompt = 37,
        MediaHandling = 38,
        MoreAppsEnabled = 39,
        MoreAppsInstallation = 40,
        MoreAppsUninstallation = 41,
        OverrideA4Letter = 42,
        PjlPassword = 43,
        RcfgEnabled = 44,
        RequestedTrayMatch = 45,
        RetrieveFromUsbEnabled = 46,
        RfuEnabled = 47,
        ServiceInvocationNotification = 48,
        SnmpRwAccessType = 49,
        SnmpV3Enabled = 50,
        Supplies = 51,
        SystemContact = 52,
        TcpIdleTimeout = 53,
        TelnetEnabled = 54,
        WebProxySettings = 55,
        WsPrintEnabled = 56
    }
}
