<?php
/**
 * DealerRemoveMailAddressFromCustomersRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mps Monitor Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DealerRemoveMailAddressFromCustomersRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DealerRemoveMailAddressFromCustomersRequest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DealerRemoveMailAddressFromCustomersRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DealerRemoveMailAddressFromCustomersRequest"
     */
    public function testDealerRemoveMailAddressFromCustomersRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dealer_code"
     */
    public function testPropertyDealerCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_hp_sds_service_request"
     */
    public function testPropertyReplaceHpSdsServiceRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_dealer_dashboard"
     */
    public function testPropertyReplaceDealerDashboard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_alert"
     */
    public function testPropertyReplaceAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_delivery"
     */
    public function testPropertyReplaceDelivery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_logistic"
     */
    public function testPropertyReplaceLogistic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replaced_consumables"
     */
    public function testPropertyReplacedConsumables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_reading_problems"
     */
    public function testPropertyReplaceReadingProblems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_installation_proposal"
     */
    public function testPropertyReplaceInstallationProposal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_re_installation_proposal"
     */
    public function testPropertyReplaceReInstallationProposal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_reading_problems_explorer"
     */
    public function testPropertyReplaceReadingProblemsExplorer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_panel_message"
     */
    public function testPropertyReplacePanelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replace_trace_volume"
     */
    public function testPropertyReplaceTraceVolume()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "update_rows"
     */
    public function testPropertyUpdateRows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
